### ISSUE TITLE
[Bug]: In Safari browse iOS devices  start and end time not come right for Microsoft365

### ISSUE THREAD

**Issue by rajkasurde** [add2cal/add-to-calendar-button#112]
### What happened?

When we pass data in start time and end time 
           startTime: '09:00',
            endTime:  '12:00',
            options: ['Apple', 'Google', 'iCal', 'Microsoft365', 'Yahoo'],
            timeZone: "Europe/Berlin",
            
            we are not getting the right start and end time.

### System & Environment

1.Device iPhone 
2.Browser safari

**Comment by jekuer** [comment]
Hi and thanks for bringing this up!

Unfortunately, this is well known, yet unaddressed bug on the Microsoft side.
For now, we have implemented a workaround, where calling MS endpoints on a mobile device would use the iCal generation instead. This would not open the webview, but could be used for any installed app. It leaves open some edge cases, but should catch the issue for the moment.
The only other working solution would require a proper backend system, which connects to the official MS API (shortly speaking - it's more complicated in the end and also out-of-scope for this JS button).
This ticket will get closed as soon as the fix has been merged.

I also started a discussion at #113 - feel free to follow for any updates.

Best,
Jens
