### ISSUE TITLE
[Bug]: "isAndroid is not defined" on selecting Outlook.com

### ISSUE THREAD

**Issue by PriyangaSG** [add2cal/add-to-calendar-button#118]
### Reason: 

The isMobile function was created with "new Function" syntax, it will execute in the global context. So calling isAndroid and isiOS methods within it will raise an error.

`const isMobile = new Function('if (isAndroid() || isiOS()) { return true; } else { return false; }');`

### Solution: 

Consider rewriting like below or in any format as long as it runs in the same lexical environment as isAndroid and isiOS methods.

```
const isMobile = () => {
	if (isAndroid() || isiOS()) {
		return true;
	} else {
		return false;
	}
};
```

### System & Environment

1. MacOS 11.6.5
2. Chrome
3. Version of the application 1.14.2 
4. Used in svelte version 3.44.0

**Comment by jekuer** [comment]
@PriyangaSG , thanks for bringing this up. Should be fixed with the latest version.

**Comment by PriyangaSG** [comment]
@jekuer, thanks for the prompt response and for investing your time in creating this incredible addon.
