### ISSUE TITLE
[Bug]: Microsoft 365 and Outlook.com buttons are not redirecting to particular pages.

### ISSUE THREAD

**Issue by prakashbokati** [add2cal/add-to-calendar-button#119]
### What happened?

Following this documentation for react does not work for Microsoft 365 and Outlook.com

### How to reproduce?

const AddtoCalendarButton: React.FC<AddtoCalendarButtonProps> = ({ event }) => {
  React.useEffect(atcb_init, [])
  return (
    <div className='atcb'>
      {'{'}
      "name":"{event.title}", "startDate":"
      {moment(event.eventDate).format('YYYY - MM - DD')}", "endDate":"
      {moment(event.endDate).format('YYYY - MM - DD')}", "startTime":"
      {moment(event.eventDate).format('HH:mm')}", "endTime":"
      {moment(event.endDate).format('HH:mm')}
      ", "location":"{event.address}", "label":"Add to Calendar", "options":[ "Apple", "Google",
      "iCal", "Microsoft365", "Outlook.com", "Yahoo" ], "timeZone":"{event.timezone}",
      "iCalFileName":"Reminder-Event", "trigger": "click"
      {'}'}
    </div>
  )
}

### Screenshots & more

Uploading Screen Recording 2022-08-10 at 17.18.32.mov…

### System & Environment

macOS,
chrome,
1.14.2

**Comment by jekuer** [comment]
Hi @prakashbokati , thanks a lot.

What exactly did not work in your case? 
Since the screen recording got not successfully attached, I am not 100% sure what this is about.

Best,
Jens

**Comment by jekuer** [comment]
@prakashbokati , there has been a fix with v.1.14.3 - would be great if you could check whether this solved your problem as well.
