### ISSUE TITLE
Multiple buttons events in one page

### ISSUE THREAD

**Issue by SeeDborg** [add2cal/add-to-calendar-button#124]
### What happened?

I try to set 4 buttons for 4 events on the same page.
With the default configuration (example 1 on your website), it's working fine, but I can't get it to work with the bring yur own button (example 7). Only the first button works.
Is there something I do wrong ?

Here is my code for the first 2 buttons for example.

### How to reproduce?

<button id="default-button1">Ajouter au calendrier</button>
                                        <script type="application/javascript">
                                          const config = {
                                            name: "test",
                                            description: "Plus d'informations",
                                            "startDate":"2023-02-14",
                                            "endDate":"2023-02-18",
                                            "startTime":"10:15",
                                            "endTime":"23:30",
                                            options: ["Google", "Apple","iCal","Microsoft365","MicrosoftTeams","Outlook.com","Yahoo"],
                                            timeZone: "Europe/Paris",
                                            trigger: "click",
                                            iCalFileName: "Reminder-Event",
                                            "inline": true,
                                            "listStyle":"modal"
                                          };
                                          const button = document.querySelector('#default-button1');
                                          button.addEventListener('click', () => atcb_action(config, button));
                                        </script>

<button id="default-button2">Ajouter au calendrier</button>
                                        <script type="application/javascript">
                                          const config = {
                                            name: "test",
                                            description: "Plus d'informations",
                                            "startDate":"2023-02-14",
                                            "endDate":"2023-02-18",
                                            "startTime":"10:15",
                                            "endTime":"23:30",
                                            options: ["Google", "Apple","iCal","Microsoft365","MicrosoftTeams","Outlook.com","Yahoo"],
                                            timeZone: "Europe/Paris",
                                            trigger: "click",
                                            iCalFileName: "Reminder-Event",
                                            "inline": true,
                                            "listStyle":"modal"
                                          };
                                          const button = document.querySelector('#default-button2');
                                          button.addEventListener('click', () => atcb_action(config, button));
                                        </script>

### System & Environment

All devices and OS

**Comment by jekuer** [comment]
Hi @SeeDborg ,

This is no bug. The script works fine with multiple custom buttons.
However, you need to make sure that the code on your side is formed properly. Check your console for the respective error messages. In your case, I would guess that the problem is using the variables `config` and `button` two times, while they are of typ `const` and therefore cannot be altered.

Check https://codepen.io/jekuer/pen/zYWmXjp for an example how your code can (!) look like.

Best,
Jens :)

**Comment by euro** [comment]
> Hi @SeeDborg ,
> 
> This is no bug. The script works fine with multiple custom buttons. However, you need to make sure that the code on your side is formed properly. Check your console for the respective error messages. In your case, I would guess that the problem is using the variables `config` and `button` two times, while they are of typ `const` and therefore cannot be altered.
> 
> Check https://codepen.io/jekuer/pen/zYWmXjp for an example how your code can (!) look like.
> 
> Best, Jens :)

@jekuer Anyway you can get this codepen example back up so I can figure out how to scope those const variables so I can put a bunch of these on one page without renaming the const values?

**Comment by jekuer** [comment]
The codepen example should be open again.
You can either use unique variables OR use "let" instead of "const". The latter option, however, might come with unwanted side effects, depending on your individual case.
