### ISSUE TITLE
[Bug]: Javascript Implementation via jsdelivr.net "SyntaxError: JSON Parse error: Unrecognized token '„'" and "Failed to load resource: the server responded with a status of 404 (Not Found)"

### ISSUE THREAD

**Issue by schottide** [add2cal/add-to-calendar-button#171]
### What happened?

Hi, I tried to implement your solution to my Wordpress as described on https://www.npmjs.com/package/add-to-calendar-button in section "Option 1: simple (CDN)".

It shows no button and in Safari Console there are two errors:

- SyntaxError: JSON Parse error: Unrecognized token '„'
- Failed to load resource: the server responded with a status of 404 (Not Found) for https://cdn.jsdelivr.net/npm/atcb.min.js.map

Hope I am not an idiot and this is a helpful report.

### How to reproduce?

The error is reproducible on [https://www.admanagerforum.de/test-add2calendar/](https://www.admanagerforum.de/test-add2calendar/ )

### Screenshots & more

<img width="673" alt="Bildschirmfoto 2022-09-08 um 09 47 49" src="https://user-images.githubusercontent.com/113093112/189065616-b09fc275-06c9-4785-ac22-99b45ffb6da9.png">

### System & Environment

Macbook Air Mac OS Monterey 
Safari Version 15.6.1 (17613.3.9.1.16)

**Comment by jekuer** [comment]
Hi @schottide , can you share the JSON block, which you are using for the button?
The problem most probably sits in an invalid JSON structure.
The missing map file shouldn't be an issue.

**Comment by jekuer** [comment]
There has been a small update with v1.15.1, which should help you to debug. It basically catches any badly formatted JSON input and tells you what to look for.
As of now, I cannot see a bug in the code. If something pops up again, feel free to open a new issue :) .
