### ISSUE TITLE
[Bug]: Google Calendar not supporting Etc Timezones

### ISSUE THREAD

**Issue by JTHEN-DEV** [add2cal/add-to-calendar-button#181]
### What happened?

When using the etc timezones e.g. Etc/GMT+8, Apple and Ical formats support the timezone. However, google calendar doesn't seem to support the timezone.

### How to reproduce?

set timeZone attribute to "Etc/GMT+8"

### System & Environment

1. Any device
2. Chrome
3. 1.15.2

**Comment by jekuer** [comment]
Thanks a lot for this catch!
This will be fixed with PR #182 and new version 1.15.3 .
