### ISSUE TITLE
Add free/busy option

### ISSUE THREAD

**Issue by neilhem** [add2cal/add-to-calendar-button#209]
Google Calendar events are all `busy` currently. Is it possible to support passing `crm` parameter
Reference: https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/main/services/google.md

**Comment by jekuer** [comment]
Put it on the roadmap.
As of now, I would call it "availability" and offer the options "free" and "busy".
Will be ignored by Microsoft and Yahoo.

**Comment by AugustDev** [comment]
Quite important feature especially for long calendar events.

**Comment by jekuer** [comment]
Implemented with new v1.18! 🥳
