### ISSUE TITLE
[Bug]: Button is not being displayed in OUTLOOK/GMAIL

### ISSUE THREAD

**Issue by Munavvar-Husein** [add2cal/add-to-calendar-button#219]
### What happened?

I have followed the documentation and used provided code to send an email from Microsoft Power Automate. After sending the email, I cannot see button in our email.
After digging it into developer tool in browser. I can see the class applied in DIV tag is being replaced with x_ i.e. x_atcb. That is why I suppose the button is not being displayed.
Please help as soon as possible.
Thank you so much in advance. :)

### System & Environment

Browser (MS Edge, Google Chrome)

**Comment by jekuer** [comment]
Just double-checking: Are you trying to run this inside of an email?
This would not work, since Javascript does not work in email HTML.

**Comment by jekuer** [comment]
Closing this due to missing response and unclear issue.
Comment if you feel there is still something to fix.

**Comment by Munavvar-Husein** [comment]
Hello @jekuer 
Thanks for the response.
Yes, we are trying to use this code in Email body.
Is there any alternative to run this button in email body?

**Comment by jekuer** [comment]
There will be soon. But with a completely different approach. Follow this repo to stay up to date.
Until that I fear there is no chance 😐
