### ISSUE TITLE
[Bug]: All day event dates are one day off on desktop, but correct on Iphone

### ISSUE THREAD

**Issue by GorkemSinirlioglu** [add2cal/add-to-calendar-button#226]
### What happened?

On Chrome 106.0.5249.119, dates are off by 1 day (minus 1 day)

I configure:
startDate: "2022-03-28",
endDate: "2022-03-29",

ICS file (Chrome):
DTSTART;VALUE=DATE:20221027
DTEND;VALUE=DATE:20221029

ICS file (other browsers):
DTSTART;VALUE=DATE:20221028
DTEND;VALUE=DATE:20221030

Unable to apply correction due to inconsistent behaviour across different browsers

### How to reproduce?

add-to-calendar-button version: 1.18.3

configure like this:
startDate: "2022-03-28",
endDate: "2022-03-29",

Open app in Chrome 106.0.5249.119

Now download ICS file, you will see:
DTSTART;VALUE=DATE:20221027
DTEND;VALUE=DATE:20221029

Also open Google Calendar -> you will see 27th October to 28
However, intented date was 28th to 29th

The problem is that it is not behaving consistently across all browsers. Otherwise, it would be easy to just add 1 day to dates for correction

Open app in any other browser (Opera, Firefox, Iphone iOS Chrome etc)
Download ICS file and you will see:
DTSTART;VALUE=DATE:20221028
DTEND;VALUE=DATE:20221030

Also open Google Calendar -> you will see 28th October to 29
So on other browsers, it works as intended. But Desktop Chrome (106.0.5249.119) is 1 day off

On top of that, I am getting following browser console log, when opening calendar (this error also happens in other browsers - not only Chrome):

![image](https://user-images.githubusercontent.com/88980869/197798265-61085d3e-b70a-4ef2-9d2d-4744d17727d4.png)

### System & Environment

add-to-calendar-button version: 1.18.3

Days display 1 day earlier (e.g. I enter 2022-03-27 as begin, but on the Google Calendar I see 26th October):
Device: PC, Windows 10, 64Bit
Browser: Chrome 106.0.5249.119

**Comment by jekuer** [comment]
@GorkemSinirlioglu , thank you for your input.
Would it be possible for you to share the whole JSON markup, which is used in your case? Thanks!

**Comment by GorkemSinirlioglu** [comment]
Hey. Sure. I will add fantasy text for name and description:

`
    atcb_action({
      name: "xxx",
      description: "yyy",
      location: "zzz",
      startDate: "2022-03-26",
      endDate: "2022-03-27",
      timeZone: "Europe/Berlin",
      options: [
        'Apple',
        'Google',
        'iCal',
        'Microsoft365',
        'MicrosoftTeams',
        'Outlook.com',
        'Yahoo'
      ],
      iCalFileName: "xxx"
    })
`

As mentioned above, any other browser gives expected results (e.g. in Google Calendar you see start 26th, end 27th)
However on Chrome 106.0.5249.119 you get 25th to 26th (both days off by 1 day)

**Comment by jekuer** [comment]
Do you see the difference only for the ical option across the browsers?
Or also at the other options (like "Google")?

**Comment by GorkemSinirlioglu** [comment]
All options behave consistently. There is no difference between Google/Microsoft/ical etc.

However, days are 1 day off in the aforementioned version of Chrome (maybe same problem exists on other browsers as well, I only observed it on Chrome)

**Comment by jekuer** [comment]
ok, thanks. Will check whether this browser calculates UTC time differently.

**Comment by GorkemSinirlioglu** [comment]
Hello
For some reason offset is showing 0, and timezone UTC. Even though my current offset is 120, and timezone is Europe/Berlin.
When I do this on other browsers, it works as expected (Europe/Berlin)

![image](https://user-images.githubusercontent.com/88980869/197877475-061a6d42-ec80-42a1-b4b8-6d6ec1d342a2.png)

**Comment by jekuer** [comment]
That's strange and most probably the root cause for the observation.
However, I could imagine to get the code a little bit more robust there. Will keep you posted

**Comment by GorkemSinirlioglu** [comment]
Loaded app with 1.18.4
![image](https://user-images.githubusercontent.com/88980869/198133991-4437d243-d1eb-4b52-aea7-41da49eb72e2.png)


Issue still persists.

**Comment by jekuer** [comment]
Unfortunately, I am no longer able to reproduce this in any way. I used different time zones in the browser and tested various edge cases.
I reverted some changes (will be part of a future release), but this should have no impact.

One final idea:
Could you share the full url, which gets generated for the Google Calendar and tell me whether the dates are hard-coded on your side or if they come dynamically from another process?

(maybe the latest Chrome update brought any change?)

**Comment by GorkemSinirlioglu** [comment]
It's not just Google Calendar. All have the same problem. When I console log the date just before hitting atcb_action, it is correct.

I am sure that the inputs I provide are correct inputs. As mentioned it's working on other devices. Only on my version of Chrome, I am having this issue where days are off by 1.

Not a big issue. Maybe it's just some extension on my browser.

**Comment by jekuer** [comment]
Ok - this was a tough one. Did you select those dates randomly or to test me? :D 

Bottom line: The issue was a calculation done with the JS Date function. Usually no problem, but a problem in your case, because the given dates are exactly where Daylight saving kicks in in Germany. Fixed by temporarily adding a time to allday events. Puhh.
Should be finally fixed with v1.18.5.

**Comment by GorkemSinirlioglu** [comment]
Lol 🤣 I know the pain. Built a web based schedule booking system that operates in any timezone. It's called Booklified. Had lots of experience in exploring bugs in such systems.

Thanks buddy! Will test this as soon as I can. If you don't hear anything from me, it worked!
