### ISSUE TITLE
[Bug]: The Google link does not properly handle times as UTC

### ISSUE THREAD

**Issue by DTallentFL** [add2cal/add-to-calendar-button#227]
### What happened?

When the link is generated it does not include the capital letter Z at the end of the times so Google calendar does not properly adjust the times to local time.
**https://calendar.google.com/calendar/u/0/r/eventedit?dates=20221205T130000/20221205T140000&**

By simply adding the Z to end of each date the new event properly shows the correct time.   
**https://calendar.google.com/calendar/u/0/r/eventedit?dates=20221205T130000Z/20221205T140000Z&**

### How to reproduce?

Click the Add To Calendar button and select Google.     The times for the start time are in UTC but formatted as HH:MM  (24 hour clock)

start time: 13:00
end time: 14:00

### System & Environment

This was done on a Windows 10 PC running Chrome.

**Comment by jekuer** [comment]
Hi, would it be possible for you to share the whole JSON content of your event? Thanks!

Theoretically, the Z should be only cut off, if there is a Timezone given. But in those cases the Timezone then should be provided to Google via the url as well

**Comment by DTallentFL** [comment]
{
      "name":"Reminder to star the add to calendar button repo",
      "description":"Some description",
      "startDate":"2023-02-14",
      "endDate":"2023-02-14",
      "startTime":"13:00",
      "endTime":"14:00",
      "location":"World Wide Web",
      "options":[
        "Apple",
        "Google",
        "iCal",
        "Microsoft365",
        "MicrosoftTeams",
        "Outlook.com",
        "Yahoo"
      ],
      "timeZone":"Etc/UTC",
      "iCalFileName":"Reminder-Event"
    }

I also included the .ics file that was created when you pick that option.
[Reminder-Event.zip](https://github.com/add2cal/add-to-calendar-button/files/9864007/Reminder-Event.zip)

**Comment by jekuer** [comment]
Thanks!
Will test tomorrow. Might be that Google is not respecting the Timezone. We already have this case with GMT zones. If I am right, it can be optimized easily.

**Comment by jekuer** [comment]
Fixed in new v1.18.4.
