### ISSUE TITLE
[Bug]: ICS file incorrectly formatted when time applied

### ISSUE THREAD

**Issue by curtismchale** [add2cal/add-to-calendar-button#228]
### What happened?

Given the following JSON while using 1.18.3:

```json
{
    "event": {
        "@context": "https:\/\/schema.org",
        "@type": "Event",
        "name": "Open Space Committee Meeting",
        "startDate": "2022-10-25",
        "endDate": "2022-10-25",
        "startTime": "17:00",
        "endTime": "19:00",
        "location": false
    },
    "label": "Add to Calendar",
    "options": [
        "Apple",
        "Google",
        "iCal",
        "Microsoft365",
        "Outlook.com",
        "MicrosoftTeams",
        "Yahoo"
    ],
    "timezone": "America\/Los_Angeles",
    "trigger": "click",
    "iCalFileName": "open-space-committee-meeting",
    "background": false
}
```

The resulting `.ics` file isn't valid. See the file output below.

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-// https://add-to-calendar-pro.com // button v1.18.3 //EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:39a30fad-f8e7-4b66-a8f2-6adea59147c8
DTSTAMP:20221025T195727Z
DTSTARTundefined:20221025T170000Z
DTENDundefined:20221025T190000Z
SUMMARY:Open Space Committee Meeting
SEQUENCE:0
STATUS:CONFIRMED
CREATED:20221025T195724Z
LAST-MODIFIED:20221025T195724Z
END:VEVENT
END:VCALENDAR
```

I'd expect to see this:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-// https://add-to-calendar-pro.com // button v1.18.3 //EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:09fc063e-1588-4484-89a1-a812248d0e1d
DTSTAMP:20221025T195130Z
DTSTART:20221025T170000Z
DTEND:20221025T190000Z
SUMMARY:Open Space Committee Meeting
SEQUENCE:0
STATUS:CONFIRMED
CREATED:20221025T195128Z
LAST-MODIFIED:20221025T195128Z
END:VEVENT
END:VCALENDAR
```

### How to reproduce?

Run the provided JSON through the atcb script.

### Screenshots & more

Removing the time does produce a valid `.ics` file for an all day event.

### System & Environment

1. macOS
2. Chrome
3. 106.0.5249.119 (Official Build) (arm64)
4. JS included manually with WordPress `wp_register_script` and then `wp_enqueue_script` where needed

register: https://github.com/proudcity/wp-proud-theme/blob/18ac7f874c026def4a2b762466b853b51e669f24/lib/setup.php#L176
enqueue: https://github.com/proudcity/wp-proud-theme/blob/18ac7f874c026def4a2b762466b853b51e669f24/lib/extras.php#L190
function called: https://github.com/proudcity/wp-proud-theme/blob/18ac7f874c026def4a2b762466b853b51e669f24/templates/content-single-meeting.php#L179

Function is actually called in many spots, but they are all similar to the link above.

**Comment by jekuer** [comment]
The problem most probably is with the Timezone. This Timezone is not valid, since it holds a backslash.
The "bug" might rather be that you get a response at all.
Could you please try to remove the backslash and try again?

Besides that, the @event markup is no longer officially supported. You should change this to a more stable scheme. Check the documentation or examples at the demo page for details.

**Comment by curtismchale** [comment]
Confirmed, updating to the newer style and this works without issues. Thanks.
