### ISSUE TITLE
[Bug]: Relax subscription protocol validation

### ISSUE THREAD

**Issue by holman** [add2cal/add-to-calendar-button#252]
### What happened?

Kind of in a chicken-or-the-egg situation right now. I've been digging into the newish support for subscriptions and it went pretty smoothly up until Google.

Google Calendar redirects to: `https://calendar.google.com/calendar/u/0/r?cid={url}`, but I'm having an issue with getting my URL accepted. For some reason, `https://` URLs don't seem to be allowed (or maybe there's a certain cert that they're looking for? StackOverflow answers were inconclusive), but `http://` and `webcal://` both work for me.

Unfortunately, add-to-calendar-button *requires* `https://` URLs as the `icsFile` value, so there's not an easy way for me to get both sides to agree on something that works. In an ideal world, I'd just use `webcal://` or `http://` (or really, figure out why Google doesn't like `https`).

### How to reproduce?

Use an URL with `https://` at the start for the value of `icsFile`.

### System & Environment

-

**Comment by jekuer** [comment]
The https requirement comes from the fact that different calendars require different protocols and https would be the least common one.
We already dynamically rewrite https to webcal for the Apple option. Therefore, it would be quite straightforward to adapt that for the Google option as well.
Can you confirm that the webcal option works on Desktop (Windows and Mac) and Mobile (iOS and Android)? Or if not, which cases can you confirm from your side? This would be really helpful! Thanks.

**Comment by holman** [comment]
Yeah, that makes sense!

I can only check `webcal://` on macOS and iOS at the moment, but both work fine.

**Comment by jekuer** [comment]
Hi @holman , have a look at the patch release v1.18.7. It hopefully fixes your issue and also a little bit more.

**Comment by holman** [comment]
Been looking into it and I'm running into something else. For some reason, on some calendars, `webcal://` prompts some other users to ask for permission to add the calendar as a subscription. So in this specific case, `webcal://` isn't workable, `https://` is apparently broken for Google Calendar, so it looks like I'm stuck wanting `http://` (which looks like it doesn't work with the latest changes).

No idea why Google decides to completely break everything like this, but ugh, such is life. :\

**Comment by jekuer** [comment]
What would be the the expected behavior in your opinion?

How I see it: It works exactly the way it should. since this is about subscribing to a calendar, it makes total sense that users see a prompt to subscribe.

If you want to share multiple events without subscription, check out the multi-date function.

If you want to share an external calendar, but without the subscription, you would need to export the calendar into one ics file (with all the dates in it) and provide this.

**Comment by holman** [comment]
It's not about the prompt- it's that it's not possible currently without changing the URL.

For example, in my use case, the *only* protocol that seems to work correctly for Google now is `http`. `https` is broken, and `webcal` gets confused and says there's not enough permissions available (but it's a public page).

So when my calendar can only be subscribed over `http`, there's not a way to use the code as-is since it shows up as an invalid url.

**Comment by jekuer** [comment]
ah, I see.
May I ask where your calendar is hosted - the one you want to share?
But yes - if your hosting server is not supporting the protocol, this will be broken.
Does it properly support https?
And one final question: How long is your calendar url?

Thinking of a fix, where you specify if you support webcal or not

**Comment by holman** [comment]
Sure! This one in particular is: https://theamericanoutlaws.com/calendar.ics

That operates correctly behind all three protocols, basically- it's just Google more or less refuses to support `https` (at all) or `webcal` (fully) for some reason, so I've been feeding `add-to-calendar-button` the `http` URL.

**Comment by jekuer** [comment]
The thing is: It is also not working with http on my side :(.
I also tested multiple own scenarios back and forth. Could not reproduce the issue with your file. Even uploading your ics file on my server works. What is not working is your URL. However, what works is adding it via Google's internal tool (not the url).
A random guess: Are you blocking any crawlers on that website (maybe only for files)?

**Comment by holman** [comment]
Super odd. The frustrating part is that there isn't any real answers from Google as to why or why not they're not doing what they should be doing, ugh.

http does work for me (as well as webcal), so maybe it's somehow per-account dependent? I don't have anything on our end that would prevent anything like this (blocking access, robots.txt, etc). Ugh.
