### ISSUE TITLE
How to integrate this code to wordpress (in front end)

### ISSUE THREAD

**Issue by yaya33130** [add2cal/add-to-calendar-button#270]
Hi, 

This is exactly what I need, but how to integrate this into my frontend ? (I'm using wordpress)

**Comment by jekuer** [comment]
@yaya33130 , good news!
WordPress plugin is now available at https://wordpress.org/plugins/add-to-calendar-button/

**Comment by jekuer** [comment]
At the moment, I would recommend to search for "add to calendar button add2cal" if you are searching for the plugin within your WP admin panel.
