### ISSUE TITLE
[Bug]: Brand icon and date box collapsed

### ISSUE THREAD

**Issue by fateslayer** [add2cal/add-to-calendar-button#275]
### What happened?

On the event selection window for multiple events, the brand icon and the date box collapsed down due to a global CSS property.

### How to reproduce?

Set the following global css property (Automatically added by a library in my case):
`*, *::before, *::after {
    box-sizing: inherit;
}`

### Screenshots & more

![image](https://user-images.githubusercontent.com/14025553/207524864-adf10508-bcf5-4fec-8fde-b823cf915071.png)

### System & Environment

1. Linux Mint OS
2. Chrome Browser

**Comment by fateslayer** [comment]
I fixed it using the following css code:
`.atcb-modal-icon,
.atcb-date-btn-left {
    box-sizing: initial;
}`

**Comment by jekuer** [comment]
Thanks for bringing this up and providing a temp. workaround!
This will be no longer an issue with the upcoming next major release.
