### ISSUE TITLE
Support of subscription calendars

### ISSUE THREAD

**Issue by HadrienKulik** [add2cal/add-to-calendar-button#36]
Excellent job on this script!

We would love to see it supporting _subscribing_ to a calendar (the feature where you can subscribe to an external dynamic .ics, for instance to load and always sync all the days off in your country with your calendar)

Addevent.com has a specific button for that: https://www.addevent.com/documentation/add-to-calendar-button-for-calendars
and I have never found a good open source alternative! 😔

**Comment by jekuer** [comment]
Implemented with new v1.18! 🥳

However, I would not consider this a very stable functionality. It works well for Google and Microsoft services. However, iCal and Apple options are a lot up to the user's device's settings. Can break very easily, so use with care!
