### ISSUE TITLE
[Bug]: Can't bind values to the properties of the component

### ISSUE THREAD

**Issue by lucasluizss** [add2cal/add-to-calendar-button#361]
### What happened?

I'm trying to use dynamic values into the properties but it cannot bind the values.

### How to reproduce?

`<add-to-calendar-button
	class="button add-calendar-btn"
	name="My event"
	[startDate]="calendarEvent.startDate"
	options="'Apple','Google','iCal'"
	startTime="10:10"
	endTime="10:40"
	timeZone="America/Los_Angeles"
	location="place"
	buttonStyle="date"
	size="5"
	lightMode="bodyScheme"
></add-to-calendar-button>`

Trying to use it with Angular, but cannot bind any of the available properties to the component.

Error: Add to Calendar Button generation failed: required setting missing [startDate]

### System & Environment

1. MacOS
2. Browser Brave
3. 2.2.2
4. Angular

**Comment by kaboume** [comment]
Same issue with Nuxtjs

**Comment by jekuer** [comment]
This is not necessarily a bug, but most probably how you are dealing (or not dealing) with the Web Component.

@kaboume , what Nuxt Version are you using?
Check out https://stackblitz.com/edit/add-to-calendar-button-nuxt-2-ssr?file=pages%2Findex.vue for a Nuxt2 version.
And in doubt, the demo in the repo for Nuxt3.

@lucasluizss , will investigate a little further for Angular.

**Comment by jekuer** [comment]
If you send me your code, I can help debugging.
Nuxt is different to Angular. Should be another issue.

The Angular issue comes up due to the order of things. The binding happens after the custom element has been parsed for the first time. This leads to the effect, that it does not re-render later.
Will apply a fix soon.

**Comment by kaboume** [comment]
Thanks;
Here is the code of my component : 


```
<script setup>
import 'add-to-calendar-button'
</script>

<template>
  <div id="myToolbar" class="d-flex justify-end">
    <div>
      <add-to-calendar-button
        name="Title"
        options="'Apple','Google'"
        location="World Wide Web"
        start-date="2023-03-09"
        end-date="2023-03-09"
        start-time="10:15"
        end-time="23:30"
        time-zone="America/Los_Angeles"
      />
    </div>
  </div>
</template>

<style scoped>

</style>

```

**Comment by jekuer** [comment]
@kaboume , you cannot use hyphens as attribute names. I know, ESLint wie Vue is crying here, but on a higher level, it is discussable here. Might catch this in the future. For the moment, sticking to the expected names should make it work.
For debugging, I would also recommend to add the `debug` flag, which provides you with more information.

**Comment by kaboume** [comment]
Ah...
I'm using Prettier / ESLing which uses hyphens...
The problem is that I don't want to disable these two vscode extensions in my project...

**Comment by jekuer** [comment]
you could simply disable this one rule. Or accept the warnings for the calendar element.

**Comment by lucasluizss** [comment]
> Ah... I'm using Prettier / ESLing which uses hyphens... The problem is that I don't want to disable these two vscode extensions in my project...

You can try to add an exception for the lines you need to use double quotes :)
e.g. `// eslint-disable-next-line $rulename`

**Comment by kaboume** [comment]
Thank you.
I'm going to try this.

**Comment by jekuer** [comment]
> Also I've found another issue regarding the Apple calendar that doesn't work with Safari

@lucasluizss , can you share more details on that? Where does it break (from a user's perspective)? Thanks.

**Comment by jekuer** [comment]
Ok, here we go.

@lucasluizss , check out the new patched version v2.2.3 - should no work with data binding. Mind that you need to use a syntax like illustrated below.
```
<add-to-calendar-button
  [attr.name]="titleVar"
  options="'Apple','Google'"
  [attr.startDate]="dateVar"
></add-to-calendar-button>
```

@kaboume , one more thought: You could also simply ignore the camel case and write "startdate" instead of "startDate". Should work and not interfere with your linter settings.

**Comment by lucasluizss** [comment]
> > Also I've found another issue regarding the Apple calendar that doesn't work with Safari
> 
> @lucasluizss , can you share more details on that? Where does it break (from a user's perspective)? Thanks.

After trying to download the apple event file it appears this error. It would be interesting to open the calendar modal for adding the event directly instead of download it.
![image](https://user-images.githubusercontent.com/22208286/223719669-65495073-4fec-4ddf-b00e-6cf08756fc21.png)

**Comment by jekuer** [comment]
@lucasluizss , thanks a lot.
Actually, this will be resolved by accident with a future update 😄 . This update might take some more time, however.

The "quick fix" - setting a time zone solves it. In doubt, simply specify `timeZone="GMT"`.

**Comment by lucasluizss** [comment]
> @lucasluizss , thanks a lot. Actually, this will be resolved by accident with a future update 😄 . This update might take some more time, however.
> 
> The "quick fix" - setting a time zone solves it. In doubt, simply specify `timeZone="GMT"`.

Nice! Thanks :)

**Comment by Koshux** [comment]
The same happens to me on Nuxt 2.17.2. Even if you add a guard to prevent a null or empty string, while it still renders the time correctly, it adds the Date before the time which is unintended behaviour and frankly unwanted.

![image](https://github.com/add2cal/add-to-calendar-button/assets/21141573/899dd0b2-62f1-47ec-b4b4-f7d4dee69196)

**Comment by jekuer** [comment]
@Koshux , what exactly is your issue?
Basically, what are you trying to do and where does it break in your opinion?

**Comment by Koshux** [comment]
> This is not necessarily a bug, but most probably how you are dealing (or not dealing) with the Web Component.
> 
> @kaboume , what Nuxt Version are you using? Check out https://stackblitz.com/edit/add-to-calendar-button-nuxt-2-ssr?file=pages%2Findex.vue for a Nuxt2 version. And in doubt, the demo in the repo for Nuxt3.
> 
> @lucasluizss , will investigate a little further for Angular.

So @jekuer, I have managed to boil down the issue to any of the following properties:
- startDate
- endDate
- startTime
- endTime

Using your stackblitz example, simply create a new data property and bind it to one of the fields above. The result is the unexpected output of the date displayed as `DD/MM/YYYY`.

![image](https://github.com/add2cal/add-to-calendar-button/assets/21141573/39eb0c20-3dce-4bfb-ba69-9bc53381e6b0)

**Comment by jekuer** [comment]
Ahh, I see.
This is done on purpose as the style of the output follows the selected language (it would look different if you would set another language).
If the output would be the same as the (very static) technical input, it would irritate most users.

**Comment by Koshux** [comment]
Personally speaking, what I am referring to as an "issue" is the fact that I cannot hide the date; not the format of it. 

Is there a way that we could disable the visibility of the appointment date, since it is visible on the left-hand side already please?

**Comment by jekuer** [comment]
Only with some css hacks at the moment.
However, the process is smarter than you might think.
We only show it, if the left date does not speak for itself. For example here, you specified 2023, which was last year. Therefore, to not confuse the user, we show the full date. For 2024, we would hide it, as the left side then indeed, would show the date already.

**Comment by Koshux** [comment]
Understood however I have this case as well with 2024, for any past, present or future date in 2024 😞
