### ISSUE TITLE
[Bug]: The location text is truncated after the comma on Apple devices (macOS, iOS)

### ISSUE THREAD

**Issue by zheniacherniavsky** [add2cal/add-to-calendar-button#365]
### What happened?

When I set a value containing a comma for the 'location' attribute, my address is truncated along with a comma for Apple Calendar. If you put a "\\" character before the comma, then for Apple calendar it will show the entire address without "\\", but for Google calendar I will see "\\" in my address.

Are there any workarounds with this?

### How to reproduce?

You can reproduce it here - https://add-to-calendar-button.com/#demo

1) Apple device (macOS, iOS)
2)
```
<add-to-calendar-button 
  name="Sample Event"
  description="Play with me!"
  startDate="2023-09-05"
  startTime="10:15"
  endTime="17:45"
  timeZone="Asia/Tbilisi"
  location="Tbilisi, Georgia"
  options="'Apple','Google','iCal','Outlook.com','Yahoo'"
></add-to-calendar-button>
```
3) Add to calendar -> Apple / iCal
4) open .ics file
5) Issue: The location text is truncated

If we set '\\' before comma:

1) Apple device (macOS, iOS)
2) 
```
<add-to-calendar-button 
  name="Sample Event"
  description="Play with me!"
  startDate="2023-09-05"
  startTime="10:15"
  endTime="17:45"
  timeZone="Asia/Tbilisi"
  location="Tbilisi\, Georgia"
  options="'Apple','Google','iCal','Outlook.com','Yahoo'"
></add-to-calendar-button>
```
3) Add to calendar -> Apple / iCal
4) open .ics file
5) Everything is fine
6) Add to calendar -> Google
7) Issue: address contains '\\'

### Screenshots & more

The issue:

![image](https://user-images.githubusercontent.com/62078242/224034008-9fc1c327-ee32-4fbb-add8-65651c3854e1.png)

Workaround with '\\':

![image](https://user-images.githubusercontent.com/62078242/224034506-246fc328-d992-410e-955f-a6508b75c720.png)

![image](https://user-images.githubusercontent.com/62078242/224035202-c9a543e8-a1e0-4932-bfee-445669aa0191.png)

### System & Environment

1. MacBook Pro (M1, Ventura 13.2)
2. Google Chrome
3. Latest application version
4. Web Component

**Comment by jekuer** [comment]
Should be fixed with v2.2.4

**Comment by zheniacherniavsky** [comment]
It works perfect, Thank you! 🚀

**Comment by fadeaway** [comment]
@jekuer This does not seem to be fixed. I tested in v2.2.4 and v.2.2.5. If you try  `\,` in the address the comma is not there and \ is.
