### ISSUE TITLE
[Feature] Set Direction of dropdown.

### ISSUE THREAD

**Issue by hayone1** [add2cal/add-to-calendar-button#371]
I think it would be nice to have the option to specify the direction of the dropdown. Perhaps that can be an option for the static drop-down option?

This is because, sometimes the bottom space is not available, or placing the dropdown up, might just make for better UX. eg.
<img width="226" alt="image" src="https://user-images.githubusercontent.com/28967086/226743166-447379c0-1fcb-40b6-8a4f-0b5ddb059c4d.png">

**Comment by jekuer** [comment]
Thanks!
Will become part of the next minor release.

**Comment by NoralK** [comment]
@jekuer Can you provide an update on this enhancement.

**Comment by jekuer** [comment]
@NoralK , has been built and will be part of the next minor release. However, this release unfortunately is not stable yet and will take some more weeks.

**Comment by hayone1** [comment]
Hi @jekuer can you give a little hint on how to use the feature or add it to the docs please. Thanks

**Comment by jekuer** [comment]
it's a new option for the listStyle attribute. see https://add-to-calendar-button.com/configuration#liststyle

Simply add the attribute like:
`listStyle="dropup-static"`
