### ISSUE TITLE
[Bug]: Outlook links not loading

### ISSUE THREAD

**Issue by bgpearman** [add2cal/add-to-calendar-button#386]
### What happened?

Hi.

When following the link to add a calendar event to Outlook, the Outlook web app hangs on this loading page:

![image](https://github.com/add2cal/add-to-calendar-button/assets/64934578/4a825d3d-7c27-4ed2-8d76-c5bb0132103c)

The link I am following is:
https://outlook.live.com/calendar/0/deeplink/compose?path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2023-11-05T21%3A15%3A00Z&enddt=2023-11-06T04%3A45%3A00Z&subject=Sample%20Event&location=World%20Wide%20Web&body=Play%20with%20me!&uid=07617985-f126-499c-b13d-1135e52ece4b

Which is the default settings on this demo:
https://add-to-calendar-button.com/#demo

I have tested both on Firefox and Chrome and the issue persists.

### System & Environment

1. Windows laptop
2. Chrome 113 / Firefox 112
3. Testing on the site demo: https://add-to-calendar-button.com/#demo

**Comment by bgpearman** [comment]
I suspect this is relevant:
https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/discussions/47#discussion-5173442

**Comment by jekuer** [comment]
We are aware of the issue linked.

However, there is another more generic thing: When you are logged in with a M365 account and try to open outlook, it will break. If you are no M365 subscriber and try to open the Microsoft link, it will also break. Even it is both Outlook under the hood, Microsoft is not able to properly redirect there at the moment.

Question to you, @bgpearman : What kind of account are you using while testing? And are you signed in with 1 or multiple accounts? If multiple, are they the same (in terms of active M365 subscription) or different?

Looking forward to your input! Thanks.

**Comment by bgpearman** [comment]
Hi Jekeur,

I have two different accounts and neither has an active M365 subscription.

If I open a private window (so no accounts signed in), follow the calendar link above, it makes me sign in. I click "yes" to the stay signed in prompt after signing in with Account A, and everything works correctly.

If I then go to the outlook web app, click "Sign in with a different account" on the top right, sign in with Account B, click "Yes" to the stay signed in prompt, then visit the calendar URL,  it also loads correctly.

Then in a new tab, follow the calendar URL, it creates correctly and under Account A.

**Comment by jekuer** [comment]
@bgpearman , so the issue appears being not in incognito mode, making use of 2 accounts in parallel (both without M365 subscription), right?

**Comment by bgpearman** [comment]
That is correct. If I repeat the same steps above but outside incognito mode, in no cases do the calendar links load correctly.

**Comment by jekuer** [comment]
Leaving out the `/0` could be an option (as pointed out in the other discussions), since the side effects feel at least better than the broken situation.
Despite that, feels like there is nothing that can be done on our side at the moment. But we will keep investigating.
Would be awesome if you could share any new insights popping up on your side. 😃

**Comment by bgpearman** [comment]
Unfortunately dropping the `/0` from the path doesn't fix the bug for me. I'll post here again if I get something working though.

**Comment by jekuer** [comment]
Fixed in v2.2.8
