### ISSUE TITLE
[Bug]: Date style is 1 day off

### ISSUE THREAD

**Issue by robertotcestari** [add2cal/add-to-calendar-button#389]
### What happened?

Date is displaying one day off

### How to reproduce?

In the playground, i am from Brazil (-3h)

### Screenshots & more

<img width="790" alt="image" src="https://github.com/add2cal/add-to-calendar-button/assets/14261421/e7584e4a-d02a-4457-a563-a9b15447fbce">

### System & Environment

1 MacOS 
2. Chrome

**Comment by robertotcestari** [comment]
Thanks!

Em qui., 11 de mai. de 2023 às 14:23, Jens Kuerschner <
***@***.***> escreveu:

**Comment by lukawefocus** [comment]
not sure if this has been resolved yet. Just want to add that the problem is related to the local browser time(zone). Just found it shows the right date in my local time CET. Opening the same webpage on my US server shows 1 day off

**Comment by jekuer** [comment]
Still relevant. Fix still done, but release pending 😉
