### ISSUE TITLE
Blank popup 

### ISSUE THREAD

**Issue by Tom01810** [add2cal/add-to-calendar-button#391]
### What happened?

Hi,

Is there any idea what causes a blank popup?
https://youtube.com/shorts/0UGG0HUle3Q?feature=share

### System & Environment

Safari on iphone

**Comment by jekuer** [comment]
What kind of system is this about? Does not seem to be about this script.
Can you share more details?

**Comment by Tom01810** [comment]
Hi, I am using WordPress.

The list of add to calendar is blank when I use it as a popup.

https://youtu.be/aR1AnsrlBy8

**Comment by jekuer** [comment]
could you please share more information on your exact configuration for the button? Also which version of the plugin you are using, as well as any browser console errors popping up. Thanks a lot!

**Comment by Tom01810** [comment]
Can you DM me on Skype?

tommy01841

I will give you the ftp and site admin info on Skype.

**Comment by jekuer** [comment]
Unfortunately, I cannot provide free individual development support.

Sharing more details here also opens up the chance that other people can jump in. It might even help other people solving their problems 🙂.

**Comment by Tom01810** [comment]
Hi, 

I fixed it.

Thank you very much for your help.
And thank you for an awesome freebie.
😄
