### ISSUE TITLE
[Bug]: Chrome Browser issue

### ISSUE THREAD

**Issue by Tom01810** [add2cal/add-to-calendar-button#394]
### What happened?

Hi,

I am not sure why it opens a blank page after adding an event to a calendar using Chrome browser
https://youtube.com/shorts/OGiuLMEl7i8?feature=share

### System & Environment

Using chrome browser on iphone

**Comment by jekuer** [comment]
Considering this spam, since it is the exact same report as 3 days ago with #391 - unless you are not providing more context and information, there is no chance to help.
