### ISSUE TITLE
[Bug]: WordPress Gutenberg block requires time zone when setting start/end time

### ISSUE THREAD

**Issue by KeanuTang** [add2cal/add-to-calendar-button#404]
### What happened?

This seems to be related to this: https://github.com/add2cal/add-to-calendar-button/issues/228

I'm using this seemingly awesome plugin in WordPress (Gutenberg block). Everything was going great until I set a start and end time for my event. The result was I could not add the event on my iPhone. When I downloaded the .ics file on my computer and opened it, I saw that the start/end dates looked like:

DTSTAMP:20230607T210451Z
DTSTARTundefined:20230903T140000Z
DTENDundefined:20230903T180000Z

The workaround for this was I added timeZone in my configuration, and now the .ics is formatting correctly.

Seems like there is a bug, or if timeZone should always be required, then documentation/the plugin should be updated accordingly.

Thanks! This plugin met a very specific need that I was surprised there doesn't seem to be more need for.

### System & Environment

WordPress 6.2.2
Latest plugin version

**Comment by jekuer** [comment]
Thanks for the observation!
Could reproduce. It is already fixed in the working branch of the upcoming release. There it falls back to UTC.

Will need to check whether a faster hotfix is worth the effort or whether we wait for the last pieces for the next bigger update...

**Comment by KeanuTang** [comment]
Sounds good. I don't need the hotfix (the workaround is good for me), so no need to rush the fix for me.

**Comment by jekuer** [comment]
@KeanuTang , solved as described with latest version of the WP plugin (1.3.2). Thanks for your feedback!
