### ISSUE TITLE
[Bug]: Issue with "add-to-calendar-button" on iOS Chrome: Inability to Copy Event Link in Production.

### ISSUE THREAD

**Issue by LirazGanon** [add2cal/add-to-calendar-button#409]
### What happened?

I am encountering an issue with the "add-to-calendar-button" feature on Chrome for iOS in the production environment. When attempting to add an event to my calendar, a modal window opens with a message indicating that the event link has been copied automatically. However, despite the message, the copied link is not available for pasting from the clipboard.

Use an iOS device (e.g., iPhone) running Chrome as the browser.
Access the production environment and navigate to [specific URL/page where the "add-to-calendar-button" is located].
Click on the "add-to-calendar-button" to initiate the event creation process.
Observe that a modal window opens, displaying a message confirming that the event link has been copied automatically.
Attempt to paste the copied event link elsewhere (e.g., in a note-taking app, messaging app, or browser URL bar).
Notice that the copied link is not available in the clipboard, despite the confirmation message in the modal window.
This issue is specific to the production environment, as the automatic link copy functionality works correctly on the development server. In the development server, the event link is copied automatically upon opening the modal and can be successfully pasted into other applications or browser windows.

### System & Environment

1. iPhone, multiply version.
2. Chrome.
3. 2.2.1.
4. import { atcb_action  } from "add-to-calendar-button";

**Comment by jekuer** [comment]
Hi @LirazGanon ,
Can you share any information on how your production setup differentiates from the dev setup?
Is there any chance to get some JS console logs?
