### ISSUE TITLE
[Bug]: Outlook Deeplinks are down.

### ISSUE THREAD

**Issue by Damien-G1** [add2cal/add-to-calendar-button#412]
### What happened?

Adding to calendar is not working

Links are being generated like this
      return '/calendar/0/deeplink/compose?path=%2Fcalendar%2Faction%2Fcompose&rru=addevent';

And calendar/0/deeplink/compose is not currently working

see: https://techcommunity.microsoft.com/t5/outlook/https-outlook-office-com-calendar-0-deeplink-compose-fails-to/m-p/3816442

### How to reproduce?

Not Working:
https://outlook.office.com/calendar/0/deeplink/compose?path=%252Fcalendar%252Faction%252Fcompose&rru=addevent&startdt=2023-05-08T03:30:00.000Z&enddt=2023-05-08T04:00:00.000Z
Working:
https://outlook.office.com/calendar/action/compose?rru=addevent&startdt=2023-05-08T03:30:00.000Z&enddt=2023-05-08T04:00:00.000Z

### System & Environment

Intel Mac Ventura
Chrome
^2.2.3
add-to-calendar-button-react

**Comment by jekuer** [comment]
This has been already resolved. The guy who has solved it at the mentioned thread was me.
Please upgrade to the latest release!
