### ISSUE TITLE
[Bug]: Unable to click the Google Calendar and iCal options in the Add to Calendar button

### ISSUE THREAD

**Issue by geekchick** [add2cal/add-to-calendar-button#413]
### What happened?

I've added the below code to my website along with the <script> tags. For some reason when I click the Add to Calendar button, I'm not able to select Google Calendar or iCal options so they get added to my calendar. Here's the page, you can try it for yourself:

https://rookietorecruit.com/rookie-to-recruit-calendar

I'm using a Mac but iPhone not working either. I'm also curious to understand why Outlook and Yahoo calendars are not showing up.

```<add-to-calendar-button
  name="[Reminder] Parents Group Coaching Call Rookie to Recruit"
  startDate="2023-07-25"
  startTime="19:00"
  endTime="20:00"
  timeZone="America/Chicago"
  location="import zoom link"
  description="Bring your college recruiting questions! This is a group coaching call for 'Parents only' in the Rookie to Recruit Membership."
  options="'Apple','Google','iCal','Outlook.com','Yahoo'"
  recurrence="RRULE:FREQ=MONTHLY;INTERVAL=1;WKST=MO;BYDAY=4TU,FR;"
  lightMode="bodyScheme"
></add-to-calendar-button>```

### How to reproduce?

1. Go to https://rookietorecruit.com/rookie-to-recruit-calendar
2. Click the Add to Calendar Button
3. Try adding the "Google Calendar" 

### Screenshots & more

![Screenshot 2023-07-07 at 3 32 32 PM](https://github.com/add2cal/add-to-calendar-button/assets/993837/9af3794f-ee7f-4a22-8975-14b13af1f779)


### System & Environment

1. Mac, OS Ventura Version 13.4.1 - Google Chrome Browser
2. iPhone 13 Pro, Version 15.5.1 - Safari browser

**Comment by jekuer** [comment]
For the Yahoo and Outlook options: They are not supported for recurring events (https://add-to-calendar-button.com/configuration#recurrence).

For the other thing, it feels like there is some element on top. Will offer a better option here in the far future.
For now: could you try placing the tag inside another div and give that div the style "display:flex; position: relative;"?
Using the listStyle="modal" option should also work.

Will have a closer look the next days.

**Comment by jekuer** [comment]
Unfortunatly, no longer able to get to the mentioned site, since it is password protected. @geekchick , is the issue still present?
