### ISSUE TITLE
[Bug]: Unable to render button when icsFile parameter starts with http://localhost

### ISSUE THREAD

**Issue by blopker** [add2cal/add-to-calendar-button#425]
### What happened?

I'm developing a Django app that allows people to subscribe to a ICS file, also hosted on the app. While developing locally, the ICS file has a url like `http://localhost:8000/event/sfsd/events.ics`. I think this is because this url is not considered valid by the `atcb_validate_icsFile` function (`!data.icsFile.startsWith('https://')`). This function seems to require a TLS URL.

I know the actual ICS url will fail to work if I actually try to add it to a calendar like Google, but for testing it would be nice to get the button to render.

Is there a solution to this? Is there a reason https is required?

### How to reproduce?

1. Use the code:

```
<add-to-calendar-button name="[Test Subscription] Add to Calendar Button" startDate="2023-07-27" subscribe icsFile="http://localhost:8000/event/sfsd/events.ics" options="'Apple','Google','iCal','Outlook.com','Microsoft 365','Microsoft Teams','Yahoo'" lightMode="bodyScheme"></add-to-calendar-button>
```

2. See the button is not rendered.

### System & Environment

Macos, Firefox, latest atcb.

**Comment by jekuer** [comment]
Simply for security reasons.
But I see the point - will lower it here.

**Comment by blopker** [comment]
Thanks for the reply! I appreciate the sentiment, but as a developer, I'd rather have this security aspect left up to me. To be fair, I noticed AddEvent uses http in their Add To Calendar button for Google calendars under some conditions. I wonder if that was an oversight...

Are you considering removing the https check outright? It seems to me that the calendars do not enforce it. If so, I'd be happy to make a PR.

**Comment by blopker** [comment]
Also, I wasn't getting any errors when this was happening, just the button wouldn't render. This was a bit confusing. I was using the minified CDN-hosted JS file though. Maybe errors are disabled there?

**Comment by jekuer** [comment]
Patch will be deployed today or tomorrow.
The errors only render, when the `debug` option is added to the button.
