### ISSUE TITLE
[Bug]: Add to calander button don`t show in Next.js 

### ISSUE THREAD

**Issue by dhasdiel** [add2cal/add-to-calendar-button#436]
### What happened?

I have a Next.js app for invatition 
i install add to calander button react to my app, but the button is hidden don't show in the page.
the code: [https://github.com/dhasdiel/invitation/blob/f-ui-add-to-cal-btn/components/ToolsButtons.tsx](url)

### Screenshots & more

![צילום מסך 2023-08-03 101325](https://github.com/add2cal/add-to-calendar-button/assets/94010236/80b34bc7-3a6f-418f-a12c-9d4654692c86)

### System & Environment

computer windows
chrome
1.0
add to calander button react

**Comment by jekuer** [comment]
Could you maybe add the `debug` attribute and share the output and console.log?

**Comment by jekuer** [comment]
Most probably it is because of how you defined the options array.
When using the React wrapper, you need to specify arrays (options, dates, images) as arrays.
-> `options={['Apple', 'Google']}`

**Comment by jekuer** [comment]
@dhasdiel what is the JS console saying?
If (with debug true) not even a red box is showing up, it seems to be something more fundamental with your React setup.
You could also try to compare it with https://stackblitz.com/edit/add-to-calendar-button-react-typescript?file=App.tsx - if you can reproduce it in a Stackblitz, where we can check it directly, we might find a solution easier 😃 .

**Comment by jekuer** [comment]
Hi @dhasdiel ,

Any progress on your side?

**Comment by dhasdiel** [comment]
Hi 
I opened it in stackblitz here is the link:
[https://stackblitz.com/github/dhasdiel/invitation?file=components%2FToolsButtons.tsx](url)
thank you for the help appreciate it very much :)

**Comment by jekuer** [comment]
Thanks a lot.
You need to add `'use client';` at top of the component!

Problem is that the button cannot be pre-rendered on server side, since it fully depends on the client. Not sure why Next is not throwing an error here (in my other test setup, it did).
