### ISSUE TITLE
[Bug]: Adding to Google Calendar on iOS and iPadOS not working properly

### ISSUE THREAD

**Issue by linh803** [add2cal/add-to-calendar-button#438]
### Expectation
Clicking on "Add to Calendar" opens up Google Calendar and loads up the new event overlay with the event info filled out
### What happened
Clicking on "Add to Calendar" opens up Google Calendar but won't load up the new event overlay unless Google Calendar is already opened in the background

### Case 1: Open event without Google Calendar in the background (BUG)
1. Close all apps
2. Open Safari -> go to the page that has the calendar button
3. Click "Add to Calendar" -> Google Calendar opens up, shows the loading bar and then does nothing else after the loading bar has finished 
### Case 2: Open event with Google Calendar in the background (WORK AS EXPECTED)
1. Open Google Calendar
2. Open Safari -> go to the page that has the calendar button
3. Click "Add to Calendar" -> Google Calendar opens up and then loads up the new event overlay while the loading bar is still showing in the background

### System & Environment

1. Devices: iPhone 12 mini (iOS 16.6) and iPad Air 4 (iPadOS 16.6)
2. Browser: Safari
3. Version number: latest
4. Setup: the Vanilla JavaScript way

**Comment by jekuer** [comment]
Unfortunately, a known issue (also see #423 ) with latest iOS (and/or Chrome on iOS) versions.
No bug on our side and unfortunately, not so much we can do right know.
Current strategy: Waiting for Big Tech to fix it - if this takes too long, maybe adding some really ugly workaround.

**Comment by jekuer** [comment]
Latest version 2.4.0 comes with a workaround, where we show a small note to the user.
Not ideal, but the best we can do from our side atm.
