### ISSUE TITLE
Programmatically Render Checkmarks

### ISSUE THREAD

**Issue by mgsgde** [add2cal/add-to-calendar-button#476]
Currently, I have some data stored in my database that indicates whether certain calendar buttons are checked or not. I want to render these checkmarks on my interface accordingly when the page loads.

**Comment by jekuer** [comment]
Hi @mgsgde ,

Unfortunately, this is not planned to be included any time soon, as it is not fitting well into the current architecture.
I would recommend you hide the checkmark of the button with the respective option and add your own element based on your data - like your own checkmark next to the button.

Best,
Jens
