### ISSUE TITLE
[Bug]: Not working for Angular server side rendering  , giving error : ERROR Error: Uncaught (in promise): ReferenceError: customElements is not defined

### ISSUE THREAD

**Issue by gauraveluminous** [add2cal/add-to-calendar-button#477]
### What happened?

Hello, I have tried to implement it on an angular 12 project,   its working fine for angular without ssr for eg for 'ng serve'  but when I use the command for server-side rendering using '`npm run dev:ssr `' OR  '`npm run build:ssr`', It's also working and showing but when I reload particular module web page then its giving error and page is just loading. 

Here are my code for reference:

EventsModule:
```

import { NgModule ,  CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { SingleEventDetailsComponent } from './single-event-details/single-event-details.component';

@NgModule({
  declarations: [SingleEventDetailsComponent , ....],
  imports: [... ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
```

single-event-details.component.html

```
  <span *ngIf="showCal">
                <add-to-calendar-button
                [attr.name]="eventTitle"
                options="'Apple', 'Google', 'iCal','Outlook.com', 'Yahoo'"
                [attr.location]="eventLocation"
                [attr.startDate]="calenderStartDate"
                [attr.endDate]="calenderEndDate"
                [attr.startTime]="eventStartTime"
                [attr.endTime]="eventendtTime"
                [attr.description]="eventDescription"
                [attr.label]="'buttons.ADD_TO_CALENDAR' | translate"
              ></add-to-calendar-button>
              </span>
```

single-event-details.component.ts

`import 'add-to-calendar-button';`

### How to reproduce?

When we reload/refresh the web page related to the events module its giving an error for SSR and page gets continuously refreshing.

Error in command prompt : 

ERROR Error: Uncaught (in promise): ReferenceError: customElements is not defined
`ReferenceError: customElements is not defined`

### Screenshots & more

![image](https://github.com/add2cal/add-to-calendar-button/assets/124558487/e8a48597-5846-4895-8f4b-67d5e00cf0cb)

### System & Environment

WEB / Windows - not checked on Safari

Browser: chrome / Firefox

Angular version: 12

**Comment by jekuer** [comment]
Hi @gauraveluminous ,

The button does not work on the server side.
To make it work in your setup, you need to integrate it in a way angular knows it is a client-only component.
Some inspiration: https://stackoverflow.com/questions/71475433/client-side-render-some-components-when-using-angular-universal

Fingers crossed this helps!

Yes, there might be smoother ways. Unfortunately, for now, it is what it is.

Best,
Jens
