### ISSUE TITLE
[Bug]: Jquery modal compatibility

### ISSUE THREAD

**Issue by bertrand-spartiad** [add2cal/add-to-calendar-button#482]
### What happened?

When the "add to calendar" module is in a jquery modal device it no longer appears.

Jquery modal modifies the DOM when a modal opens.
I have the impression that at this moment the add-to-calendar is destroyed

`Add to Calendar Button "atcb-btn-45" created, Add to Calendar Button "atcb-btn-45" destroyed, Add to Calendar Button "atcb-btn-45" destroyed`

With the old version of the module I used atcb_init in this case to force a refresh. But the function no longer exists on this version.

### How to reproduce?

Open by default a jquery modal with the module in content

With 

### System & Environment

Chrome

**Comment by jekuer** [comment]
Hi @bertrand-spartiad ,
Would not consider it a bug based on the description. Maybe would need some Stackblitz or codepen to reproduce.

What you could try:
1) insert the tag programmatically one the modal is open.
2) add the attribute "instance" and simply count it 1 up when the modal opens. This would trigger a re-rendering. However, might not work if the whole web component gets somehow removed by jQuery

**Comment by jekuer** [comment]
Closing it due to inactivity.
The instance attribute will get its own part in the documentation.
