### ISSUE TITLE
[Bug]: Outlook.com didnt work properly

### ISSUE THREAD

**Issue by dogukanakin** [add2cal/add-to-calendar-button#496]
### What happened?

When I click on Outlook.com it asks me to log in again even though my account is open

### Screenshots & more

<img width="1673" alt="Ekran Resmi 2023-10-30 15 07 14" src="https://github.com/add2cal/add-to-calendar-button/assets/101465660/eab00dab-16a9-429b-933f-e2a61f3b5c2f">

### System & Environment

browser(chrome)

**Comment by korayguler8989-cyber** [comment]
> ### What happened?
> 
> When I click on Outlook.com it asks me to log in again even though my account is open
> 
> ### How to reproduce?
> 
> _No response_
> 
> ### Screenshots & more
> 
> <img width="1673" alt="Ekran Resmi 2023-10-30 15 07 14" src="https://github.com/add2cal/add-to-calendar-button/assets/101465660/eab00dab-16a9-429b-933f-e2a61f3b5c2f">
> 
> 
> 
> ### System & Environment
> 
> browser(chrome)

Font

**Comment by korayguler8989-cyber** [comment]
> ### What happened?
> 
> When I click on Outlook.com it asks me to log in again even though my account is open
> 
> ### How to reproduce?
> 
> _No response_
> 
> ### Screenshots & more
> 
> <img width="1673" alt="Ekran Resmi 2023-10-30 15 07 14" src="https://github.com/add2cal/add-to-calendar-button/assets/101465660/eab00dab-16a9-429b-933f-e2a61f3b5c2f">
> 
> 
> 
> ### System & Environment
> 
> browser(chrome)

Funt
