### ISSUE TITLE
[Bug]: .ics does not handle [ul][/ul]

### ISSUE THREAD

**Issue by EBerthaud** [add2cal/add-to-calendar-button#499]
### What happened?

Hi,

I'm trying to use some lists into my event's description. I use [ul] and [li] as from the documentation. But once importing an .ics file into my iCal, lists seems not to be translated.
Trying it into the [demo](https://add-to-calendar-button.com/#demo) page is reproducing the bug.

### How to reproduce?

Go to the demo page
Set as description: ```Title [ul][li]item 1[/li] [li]item 2[/li] [li] item 3[/li][/ul]```

Add to google calendar -> working well (screenshot 1)

Add to Apple calendar -> The list is not formatted (screenshot 2)

### Screenshots & more

<img width="777" alt="Screenshot 2023-11-15 at 15 39 24" src="https://github.com/add2cal/add-to-calendar-button/assets/144008723/b253b4e1-b5ae-4b71-a04e-dcfd0e70e87d">

<img width="312" alt="Screenshot 2023-11-15 at 15 39 36" src="https://github.com/add2cal/add-to-calendar-button/assets/144008723/b927ebf9-86ff-4bc1-9b6f-3ad7e974c1fa">

### System & Environment

1. MacOS 13.5.1
2. Any browser
3. Version 2.4.3

**Comment by jekuer** [comment]
Hi @EBerthaud ,

Thank you for your message!
Unfortunately, this is no bug. It is a missing feature on Apple's side. They only support line breaks and hyperlinks at the moment.
As this is something people wish them to fix for years now, I would not expect anything to change - Apple being Apple.
I will update the docs soon to be more precise on that circumstance.

All the best,
Jens
