### ISSUE TITLE
[Bug]: Chrome on iOS not opening Apple calendar

### ISSUE THREAD

**Issue by mhaszprunar** [add2cal/add-to-calendar-button#501]
### What happened?

Tried the "Apple" option on Chrome on iOS. There is an error message saying that you need to copy some text into the clipboard and then open Safari and paste it there. Very inconvenient.
Any chance to get this working on Chrome for iOS without manual copy&paste?

### System & Environment

iPhone
iOS
Browser: Chrome
selected option "Apple calendar"

**Comment by mhaszprunar** [comment]
Thanks for the fast response! Crazy how Apple can make this very annoying for people using other browsers...
Looking forward to the PRO verison, do you already have more information about it?

**Comment by jekuer** [comment]
Hi @mhaszprunar , 

Just published the PRO version.
Check it out at https://add-to-calendar-pro.com!

Looking forward to your feedback.
Jens
