### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vladimircherevko** [add2cal/add-to-calendar-button#503]
### What happened?

I'm trying to add attendee to google calendar via atcb_action(config). It has "organizer " & "attendee", but the attendee doesn't appear in the calendar (as i can see it doesn't appear in request params at all). Is it expected behavior?

### System & Environment

1. macOS Ventura 13.2.1
2. Chrome

**Comment by jekuer** [comment]
Yes, it is.
The attendee option only affects the ics file. There, it can be useful to make an event being saved to the calendar als already accepted. Such behavior is not necessary for other calendar types, as there is not status as with ics.

So far, I was not aware of a use case for an Add to Calendar Button to push attendees to a Google Event.


Related Discussions:

- https://github.com/add2cal/add-to-calendar-button/discussions/465
- https://github.com/add2cal/add-to-calendar-button/discussions/380

**Comment by vladimircherevko** [comment]
Thanks.

**Comment by vladimircherevko** [comment]
Thanks. Not clear enough what is problem to use "add=" query of google API for attendee. I'm not profi in it

**Comment by jekuer** [comment]
No technical problem. But it changes the whole nature of the process. The event would than no longer be an event to add to your calendar, but a draft for an event invite.
This makes no sense from a product management perspective.

But maybe we are missing some use case - if you want to share your case, this would help a lot.
