### ISSUE TITLE
[Bug]: Multiple [url]s in description causes missing text in iCal plain text description

### ISSUE THREAD

**Issue by jaronheard** [add2cal/add-to-calendar-button#509]
### What happened?

If there is more than one [url] in a description, the plain text portion of description in the iCal file that Apple Calendar uses cuts everything after the first [url] until after the last [url].

### Input - Single Link
`text before first link [url]https://first.com|first link[/url] text after first link`
### ✅ Output
text before first link https://first.com text after first link
### Input - Two Links
`text before first link [url]https://first.com|first link[/url] text after first link [url]https://second.com|second link[/url]`
### ❌ Output
text before first link https://first.com
### Input - Two Links With Text After
`text before first link [url]https://first.com|first link[/url] text after first link [url]https://second.com|second link[/url] text after second link` 
### ❌ Output
text before first link https://first.com text after second link
### Input - Three Links
`text before first link [url]https://first.com|first link[/url] text after first link [url]https://second.com|second link[/url] text after second link [url]https://third.com|third link[/url] text after third link` 
### ❌ Output
text before first link https://first.com text after third link

### How to reproduce?

Copy/paste the inputs above into the description field of the [hosted demo](https://add-to-calendar-button.com/#demo), then click the Apple button to download an iCal file and inspect it. Opening in Apple Calendar will expose the issues as well.

### System & Environment

[hosted demo](https://add-to-calendar-button.com/#demo), but also present in my custom application.

**Comment by jaronheard** [comment]
A few additional notes:
- This issue only appears with hyperlinks that use the HTML psuedo tag schema. So examples with multiple links in plain text don't cause issues. So this example description would work fine: `text before first link https://first.com text after first link https://second.com text after second link`
- There are no issues that I've encountered with multiple links in Google Calendar
- This issue only shows up in the plain test portion of the DESCRIPTION, it is fine in the `X-ALT-DESC;FMTTYPE=html` section

### Full `DESCRIPTION` from the `Three Links` example iCal file:
```
DESCRIPTION:text before first link https://first.com text after third li
 nk
X-ALT-DESC;FMTTYPE=text/html:
 <!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 3.2//EN"">
 <HTML><BODY>
 text before first link <a href="https://first.com" target="_
 blank" rel="noopener">first link</a> text after first link <
 a href="https://second.com" target="_blank" rel="noopener">s
 econd link</a> text after second link <a href="https://third
 .com" target="_blank" rel="noopener">third link</a> text aft
 er third link
 </BODY></HTML>
 ```

**Comment by jekuer** [comment]
Hi @jaronheard ,

Thanks a lot!
This was a very good catch and an extremely (!) well written bug report.
Issue has been fixed and fix will be part of the next big release, coming mid of next week. 🚀 

All the best!
Jens
