### ISSUE TITLE
[Bug]: image add-to-calendar-button.com is added in the build script

### ISSUE THREAD

**Issue by devhaywoodtech** [add2cal/add-to-calendar-button#524]
### What happened?

`imageData.push('\"https://add-to-calendar-button.com/demo_assets/img/1x1.png\"');\n      imageData.push('\"https://add-to-calendar-button.com/demo_assets/img/4x3.png\"');\n      imageData.push('\"https://add-to-calendar-button.com/demo_assets/img/16x9.png\"')`

I have used the following code 
```
<add-to-calendar-button
                name={title}
                options="'Google','Apple','iCal','Outlook.com','Yahoo','Microsoft365','MicrosoftTeams'"
                location={address}
                startDate={format(fromUnixTime(startDate), 'yyyy-MM-dd')}
                endDate={format(fromUnixTime(endDate), 'yyyy-MM-dd')}
                startTime={format(fromUnixTime(startDate), 'kk:mm')}
                endTime={format(fromUnixTime(endDate), 'kk:mm')}
                timeZone="currentBrowser"
                hideCheckmark
                hideBranding={true}inline
                listStyle='overlay' /> 
```

### How to reproduce?

Why the image from the add-to-calendar-button.com is added on the build. Also it had added on the <script type="application/ld+json"> as  well.
How to remove this on build and <script type="application/ld+json">?

### System & Environment

All browsers
React Wrapper
"add-to-calendar-button": "^2.3.4",

**Comment by devhaywoodtech** [comment]
Here is the schema
```
<script type="application/ld+json">{
"@context":"https://schema.org",
"@type":"Event",
"name":"Event 1",
"startDate":"2024-01-01T13:00:00+05:30",
"duration":"154:00",
"location":"Venue 1 Address Change 1, Venue 1 City, Venue 1 State, AE, 44224",
"endDate":"2024-01-07T23:00:00+05:30",
"image":[
"https://add-to-calendar-button.com/demo_assets/img/1x1.png",
"https://add-to-calendar-button.com/demo_assets/img/4x3.png",
"https://add-to-calendar-button.com/demo_assets/img/16x9.png"]
}</script>
```

**Comment by devhaywoodtech** [comment]
I tried new version 2.5.5. 
Still the same result on build file

**Comment by jekuer** [comment]
This is a fallback for the schema.org data.
Try to add `images="[]"` to the button. This should remove the fallback.

**Comment by jekuer** [comment]
Since there was no more feedback, I consider this answered and closed. In case there are more issues around that, I am happy to reopen it.
