### ISSUE TITLE
[Bug]: Outlook shows '&' character in the name as '&amp;' 

### ISSUE THREAD

**Issue by Samaa-Amin** [add2cal/add-to-calendar-button#529]
### What happened?

if the name value contains '&', it shows as '&amp;' in outlook only

### How to reproduce?

include '&' character in the name and add to calendar via outlook 

### Screenshots & more

![image](https://github.com/add2cal/add-to-calendar-button/assets/60674022/8248afe7-0baf-4b35-950b-f03b3a8747c4)

### System & Environment

I'm using "add-to-calendar-button-react" latest version (2.5.5), this issue happens on all devices

**Comment by jekuer** [comment]
Unfortunately, this is an Outlook issue. We are transmitting the ampersand (&) in the only possible and stable way, encoding it as %26.
Somehow, Microsoft does not parse it correctly (but only for the event subject/title.

We will publish a workaround asap, which replaces any ampersand in the title with a similar looking HTML special character.

**Comment by jekuer** [comment]
Fixed with v2.5.7

**Comment by jekuer** [comment]
Ah, sorry. For the React wrapper, it is v2.5.6
