### ISSUE TITLE
[Bug]: Providing start time without end time causes component to not render

### ISSUE THREAD

**Issue by SpiritSeal** [add2cal/add-to-calendar-button#534]
### What happened?

When initializing a button, including a startTime parameter wtihout an endTime parameter causes the component to not render.

### How to reproduce?

Minimal reproducible examples:

The following renders:
```
              <AddToCalendarButton
                name={value.event_details.event_title}
                startDate={value.event_details.event_start_date}
                startTime={value.event_details.event_start_time}
                endTime={value.event_details.event_end_time}
              />
```
The following does not render:
```
              <AddToCalendarButton
                name={value.event_details.event_title}
                startDate={value.event_details.event_start_date}
                startTime={value.event_details.event_start_time}
                // endTime={value.event_details.event_end_time}
              />
```

### System & Environment

Windows 11, Microsoft Edge
Using React Wrapper Library

**Comment by jekuer** [comment]
This is no bug.
When adding the debug option, it would tell you that the end time is mandatory if a start time is set.
That's basically because if an event is no all-day event, it requires a time slot, which always has a start and an end time.
