### ISSUE TITLE
[Bug]: subscribe: false with icsFile is opening webcal:// URL not https

### ISSUE THREAD

**Issue by alexcroox** [add2cal/add-to-calendar-button#536]
### What happened?

I'm bypassing a webview when opening a single event with the "Apple" button. I'm providing my own `icsFile` URL, but `https` is being replaced with `webcal://` when opening Safari meaning the Apple calendar app is trying to subscribe to a URL instead of opening the ics single event. Is there way to specify the protocol (webcal or https) when linking to an icsFile?

Note `subscribe: false`. If it was true I would expect the webcal:// replacement.

```
<add-to-calendar-button
  :icsFile="singleEvent.icsFileUrl"
  :name="singleEvent.title"
  options="'Apple', 'Google', 'iCal', 'Microsoft365', 'MicrosoftTeams', 'Outlook.com', 'Yahoo'"
  :location="singleEvent.location"
  :iCalFileName="`${singleEvent.title} ${singleEvent.startDate}`"
  buttonStyle="round"
  hideIconList
  inline
  buttonsList
  hideBackground
  hideCheckmark
  bypassWebViewCheck
  :subscribe="false"
  :startDate="singleEvent.startDate"
  :endDate="singleEvent.endDate"
  :startTime="singleEvent.startTime"
  :endTime="singleEvent.endTime"
  timeZone="Europe/London"
></add-to-calendar-button>
```

### System & Environment

iPhone 15, Capacitor.js webview

**Comment by jekuer** [comment]
This got added on purpose as a workaround, since (last time we checked) Apple did not play nice with https and ics outside of Safari.
No ideal solution, but best thing to get at the moment.

Do you know what happens, when you add a simple hyperlink with the ics file address and https protocol?
Maybe they changed something in the meantime.

**Comment by alexcroox** [comment]
Seems to work ok for me on the latest iOS. 

Video: 

https://github.com/add2cal/add-to-calendar-button/assets/1065835/64032c16-6e0c-4185-bf76-7052587eb0b5

**Comment by jekuer** [comment]
Confirmed that it is now working quite nicely (except for Firefox on iOS, but I think that is acceptable).
Will revert soon!

Thanks for your support!

**Comment by alexcroox** [comment]
great news thanks!

**Comment by jekuer** [comment]
Rollout will be next week.
In case that is too late, you would need to clone the current dev branch.

**Comment by alexcroox** [comment]
Amazing thank you!!
