### ISSUE TITLE
[Bug]: buttonStyle="date" does not respect listStyle

### ISSUE THREAD

**Issue by pleasantone** [add2cal/add-to-calendar-button#542]
### What happened?

Trying to use add2cal with button style set to date, and the top of the box is getting clipped because of other bits on my website. listStyle is respected properly with the default but not buttonStyle date.

### How to reproduce?

Set buttonStyle="date" and listStyle="dropdown-static" and instead you get overlay behavior.

### Screenshots & more

<img width="322" alt="Screenshot 2024-01-22 at 10 44 53 PM" src="https://github.com/add2cal/add-to-calendar-button/assets/5339793/a1790243-90b3-4d52-8697-3ba64de983bc">
<img width="342" alt="Screenshot 2024-01-22 at 10 44 59 PM" src="https://github.com/add2cal/add-to-calendar-button/assets/5339793/878e20bb-c49a-46df-b311-41eafc189f74">

### System & Environment

MacOS / Safari 17.2

**Comment by pleasantone** [comment]
Line 211 in atcb-decorate;

```
    // for the date style, we even block the dropdown completely and fall back to overlay
    if (data.buttonStyle == 'date' && isDropdown) {
      data.listStyle = 'overlay';
    }
```

Why?

**Comment by jekuer** [comment]
The reason behind that were a lot of rendering issues due to the dynamic nature of the date button.
However, this changed a little bit in the more recent past. It makes sense to change this again and leave it up to the user.

Will be part of one of the next releases.

**Comment by jekuer** [comment]
Updated with v2.5.9
