### ISSUE TITLE
Times getting skewed in Microsoft Office

### ISSUE THREAD

**Issue by bh3605** [add2cal/add-to-calendar-button#556]
Great library! Fun working with so far.

Let's say I have a Microsoft Office calendar url like so
https://outlook.office.com/calendar/action/compose?rru=addevent&startdt=2024-02-29T15:00:00Z&enddt=2024-02-29T16:00:00Z&subject=location=Health&body=This%20is%20a%20reminder

For the time it should be 10:00AM - 11:00AM, but for some reason it's making it 7:00AM - 8:00AM. Any advice on what's causing the time to adjust even though <code>new Date("2024-02-29T15:00:00Z").getHours()</code> returns 10? The time is absolutely right in the url, but something else is changing it.

**Comment by jekuer** [comment]
Hi @bh3605 ,
Can you please double-check the time zone in Outlook?
Mind that Outlook does not necessarily adapt to the time zone on your computer. In most cases, there is a mismatch.

**Comment by bh3605** [comment]
Thanks a lot! I'll probably have to warn my users their time zone settings could create a meeting with the wrong time.

**Comment by jekuer** [comment]
It will never be the wrong time. It is always the correct time in the respective time zone 😉.

The advice would be to double-check that the calendar and watch are configured properly.
If this is not the case, any event would be "wrong" - not only yours.
