### ISSUE TITLE
[Bug]: Timezone doesn't display when start/end time is "dynamic"

### ISSUE THREAD

**Issue by bh3605** [add2cal/add-to-calendar-button#558]
### What happened?

There's an example showing the timezone
``` html
<add-to-calendar-button
  name="My awesome Event"
  startDate="2024-03-08"
  options="'Apple','Google','iCal'"
  startTime="10:10"
  endTime="10:40"
  timeZone="America/Los_Angeles"
  location="Fantasy Marketplace"
  buttonStyle="date"
  size="5"
  lightMode="bodyScheme"
></add-to-calendar-button>
```
I tried following suit with my button, but the timezone won't display. I calculate the start and end times so I can't write a concrete value to either one. I think that's causing something to bug and not render the timezone once a start and end time are added

### How to reproduce?

``` html
<add-to-calendar-button options="'Apple','Google','Outlook.com','Microsoft365','Yahoo'"
  name="Onboarding Screening" [attr.description]="description" [attr.startDate]="startDate" [attr.location]="location"
  [attr.startTime]="startTime" [attr.endTime]="endTime" timeZone="America/New_York" debug="true"
  forceOverlay="true" hideBranding="true" lightMode="bodyScheme" buttonStyle="date" size="5">
</add-to-calendar-button>
<br/>
<add-to-calendar-button
  name="My awesome Event"
  startDate="2024-03-08"
  options="'Apple','Google','iCal'"
  startTime="10:10"
  endTime="10:40"
  timeZone="America/Los_Angeles"
  location="Fantasy Marketplace"
  buttonStyle="date"
  size="5"
  lightMode="bodyScheme"
></add-to-calendar-button>
```
``` typescript
export class MyCalButton {
  startDate = (new Date()).toISOString().split('T')[0];
  startTime;
  endTime;
  location = "location name"
  description = `This is a reminder of your following appointment `;

  public constructor() {
    this.startTime = "09:50";
    this.endTime = "10:45";
  }
}
```
![image](https://github.com/add2cal/add-to-calendar-button/assets/3073436/65341dd5-c109-4c26-ba3e-87dacffc5686)

### System & Environment
Angular 16
Chrome

**Comment by jekuer** [comment]
How does it look like when you also use the time zone "America/Los_Angeles" in your first example?
Background: We do not show the time zone when it is the same as your browser is in.

**Comment by bh3605** [comment]
Ohhh now it appears. Good to know! Maybe you could add a flag to override that timezone hiding behavior?

**Comment by jekuer** [comment]
Or maybe something like a custom template to define which blocks to show on this kind of button.
If you have some ideas and cases, it would be cool if you could open up a discussion. Then we can collect feedback from other people to see whether this is a thing or not.

Will close this issue here as it got resolved.
