### ISSUE TITLE
Add a variable for text-align for modal multidate text

### ISSUE THREAD

**Issue by minisemi** [add2cal/add-to-calendar-button#559]
The multidate text in the modal is left aligned, while all the other content is centered, which makes it look very out of place:

<img width="538" alt="image" src="https://github.com/add2cal/add-to-calendar-button/assets/4705200/dd17d81d-9667-4433-82b9-12ac092d0994">

Please make its text-align attribute a variable that can be overridden so we can set it to 'center'.

**Comment by jekuer** [comment]
Added with latest v2.6.1
