### ISSUE TITLE
[Bug]: subscribe button doesn't render unless there is a startDate

### ISSUE THREAD

**Issue by justin-hackin** [add2cal/add-to-calendar-button#572]
### What happened?

When using react component to create an ics subscribe button, the component doesn't render unless there is a startTime. It's confusing, why does a subscription need a start time? The typescript types don't seem to indicate this as a required property either.

### How to reproduce?

Render this:
```
<AddToCalendarButton
		name={'Cal'}
		options={['Apple', 'Google', 'Yahoo', 'iCal']}
		icsFile={'http://......'}
		subscribe
	></AddToCalendarButton>
```

and then observe button doesn't render. Add startDate, notice button renders.

### System & Environment

1. Apple M1 , macOS Ventura Version 13.4 (22F66) , Chrome Version 122.0.6261.129 (Official Build) (arm64), package version `"add-to-calendar-button-react": "^2.6.8",`  via npm

P.S. It's better to populate this with template text rather than use a placeholder to list requirements because as soon as the reporter types anything they lose sight of the requirements.

**Comment by jekuer** [comment]
Changed with v2.6.9

**Comment by justin-hackin** [comment]
> Changed with v2.6.9

Thanks for addressing this 🎉
