### ISSUE TITLE
[Bug]: Button not visible.

### ISSUE THREAD

**Issue by Sahil-Sharma-23** [add2cal/add-to-calendar-button#592]
### What happened?

The 'add to calendar button' for NextJS project just does not appear on the screen. Tried all the ways possible mentioned in the doc, still the button is not visible.

### How to reproduce?

Follow the docs for NextJS installation.
https://add-to-calendar-button.com/use-with-nextjs

### Screenshots & more

![image](https://github.com/add2cal/add-to-calendar-button/assets/64127015/63566a30-0a8a-4f9a-a0de-b644cfad823f)

### System & Environment

1. Device and OS: Windows 10 Pro
2. Browser: Chrome

**Comment by jekuer** [comment]
Have a look at https://stackblitz.com/edit/add-to-calendar-button-next-js
This should explain a lot. I guess you are not using "use client"

**Comment by Sahil-Sharma-23** [comment]
Yes. Thanks. My issue is resolved.
Also a suggestion, You can update the doc on website and mention that this component needs to be implemented in a client component.
