### ISSUE TITLE
[Bug]: wrong date displayed in the event series preview if timezone is west of UTC

### ISSUE THREAD

**Issue by ets-ann** [add2cal/add-to-calendar-button#593]
### What happened?

Wrong date is displayed in the event series preview if the timezone of the browser/device is west of UTC, e.g. PST.

### How to reproduce?

**Prerequisites:**

1. Create an event series using dates. Please, see [code example](https://stackblitz.com/edit/vitejs-vite-bactwh?file=index.html) 
2. The events must be all day events, so there is only startDate. 
3. The timezone of the device is negative to UTC, e.g. PST.

**Steps to reproduce:**
1. Click Add to Calendar.
4. Click Google or Yahoo, so 'This is an event series' pop up is open.
5. Compare displayed dates in the pop up and actual dates in startDate.

**Actual result:**
the dates are not the same.

**Expected result:**
the dates in the pop up and in startDate should be the same as it is an all day event, and it should not depend on the timezone of the user/device.

### Screenshots & more

<img width="1720" alt="event-series-bug" src="https://github.com/add2cal/add-to-calendar-button/assets/160623733/9da4f057-d4ac-4012-8b41-8134159d1d29">

### System & Environment

1. Device and OS: all 
2. Browser: Chrome, Safari
3. Version number of the application: all versions
4. How you include the script:

**Comment by jekuer** [comment]
Thanks. Fixed with latest patch release! :)
