### ISSUE TITLE
[Bug]: Yahoo event is not displayed as an All Day event if there is a startDate only

### ISSUE THREAD

**Issue by ets-ann** [add2cal/add-to-calendar-button#596]
### What happened?

When adding to Yahoo and when there is just a startDate only, the event is not added as an All day event.

### How to reproduce?

**Prerequisites:**

1. Create an event series using dates or just one event. Please, see [code example](https://stackblitz.com/edit/vitejs-vite-bactwh?file=index.html) 
2. The events must be all day events, so there is only a startDate.

**Steps to reproduce:**

1.  Click Add to Calendar in the Multiple Events.
2. Click Yahoo, so 'This is an event series' pop up is open.
3. Click any event, so Yahoo mail is opened.
or
1.  Click Add to Calendar in the Single Yahoo Event.

**Actual result:**
The event is not added as an all day event.
<img width="1245" alt="yahoo_actual" src="https://github.com/add2cal/add-to-calendar-button/assets/160623733/4782fc30-8cd1-4da0-b5e8-881cdf2c80c1">

**Expected result:**
The event is added as an all day event and all day event toggle is active.
<img width="1197" alt="yahoo_expected" src="https://github.com/add2cal/add-to-calendar-button/assets/160623733/11d0fdbd-f118-407f-b66a-74cd1d8e8fec">

### System & Environment

1. Device and OS: all
2. Browser: all
3. Version number of the application: 
4. How you include the script:

**Comment by jekuer** [comment]
@ets-ann , thanks!
Resolved (via workaround as this clearly is a bug on Yahoo's side) with v2.6.15 🚀
