### ISSUE TITLE
[Bug]: Angular - offset calculation failed: time misspelled [-> hh:mm]

### ISSUE THREAD

**Issue by phgimenez** [add2cal/add-to-calendar-button#608]
### What happened?

I'm having this error:
Add to Calendar Button generation (my-default-button) failed: time misspelled [-> HH:MM]

When executing this code in Angular v17:

```
    addToCalendar() {
      const config: ATCBActionEventConfig = {
        name: "[Reminder] Test the Add to Calendar Button",
        description: "Check out the maybe easiest way to include Add to Calendar Buttons to your web projects:[br]→ [url]https://add-to-calendar-button.com/|Click here![/url]",
        startDate: "2024-07-19",
        startTime: "10:15",
        options: ["Google", "iCal"],
        timeZone: "America/Los_Angeles",
        created: "20240716T100000Z",
        updated: "20240716T100000Z"
      };
      const button = document.getElementById('my-default-button');

      atcb_action(config, button)
    }
```

I've tried setting endDate, endTime aswell but also fails. Removing created or updated properties ends in a different exception.

### System & Environment

1. Device and OS: Windows 10
2. Browser: Chrome
3. Version number of the application: 2.6.18
4. How you include the script: https://add-to-calendar-button.com/use-with-angular

**Comment by jekuer** [comment]
Not sure what is wrong with your code.
I tried to replicate it without success.
Can you have a look at my simple setup at https://stackblitz.com/edit/add-to-calendar-button-angular-pq3ac1?file=src%2Fmain.ts and check where's the difference to your setup?

Btw: One difference for sure is the endTime, as this is required when there is a startTime (but the console would say so).

**Comment by phgimenez** [comment]
Thank you for your support. I found code in my project that modifies Date.prototype.toISOString, Date.prototype.toString, and DateTime.prototype.toString.

This seems to break the add-to-calendar-button functionality.
