### ISSUE TITLE
[Bug]: [url] tag is not rendered correctly

### ISSUE THREAD

**Issue by coodde** [add2cal/add-to-calendar-button#615]
### What happened?

When for description attribute you will use emoji or non-latin symbols it will be not rendered.

### How to reproduce?

set description value as "Click [url]https://coodde.com/mental-health|посилання[/url]" or "Click [url]https://coodde.com/mental-health|💻 link[/url]" and try to click on "Google Calendar" button. You will see descirption with not rendered [url] tag

### System & Environment

1. Device and OS: any
2. Browser: any
3. Version number of the application: 2.6.18
4. How you include the script: TS in the vue app

**Comment by jekuer** [comment]
Resolved with latest update
