### ISSUE TITLE
[Bug]: Doesn't render initial button in Google Maps InfoWindow

### ISSUE THREAD

**Issue by ProLoser** [add2cal/add-to-calendar-button#616]
### What happened?

I'm creating a page with google maps api. I'm creating an InfoWindow (popup) when the user clicks on a map marker that contains the add-to-calendar button.

I followed the installation and configuration instructions but I do not see a button. I do see a little bit of shadow DOM and some attributes that show that the tag IS recognized but I do not understand why it's not rendering a button.

See these lines on my implementation https://github.com/ProLoser/funcheapmap/blob/gh-pages/map.js#L161-L174

### How to reproduce?

You can access the site online here https://proloser.github.io/funcheapmap/ clicking on a marker should show the InfoWindow. If you inspect the InfoWindow just above the "+ Expand Details +" link you will see your tag but no text or other elements

### Screenshots & more

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/546443d0-c299-4d0d-bcb3-e30b8f5031be">

### System & Environment

1. Device and OS: OSX Macbook Pro
2. Browser: Chrome
3. Version number of the application: latest online copy
4. How you include the script: cdn script tag

**Comment by jekuer** [comment]
Add the `debug` option to get more hints on what's wrong. In the case above, no endTime is set - this is mandatory if you set a startTime.
