### ISSUE TITLE
[Bug]: Button no visible when using AddToCaledarButton inside a component with values for startTime and endTime passed as props.

### ISSUE THREAD

**Issue by itsritiksharma** [add2cal/add-to-calendar-button#622]
### What happened?

When using `AddToCalendarButton` from `add-to-caledar-button-react` inside a component with startTime and endTime passed as props, the button is not visible on the screen.

### How to reproduce?

1. Create a component for the `AddToCalendarButton` accepting `startDate`, `endDate`, `startTime` and `endTime` as props. 
2. Pass those values in `AddToCalendarButton` for `startDate`, `endDate`, `startTime` and `endTime` properties.

You'll see that the button is rendered in the dom by inspecting but it's not visible on the webpage for some reason.

Note: It's working fine when only passing `startDate` and `endDate` but as soon as we pass `startTime` or `endTime` the button disappears from the webpage.

https://replit.com/@ritiksharma102/AddToCalendarIssue?v=1

### Screenshots & more

![image](https://github.com/user-attachments/assets/9bb891b2-55ee-495d-a0be-7b45a9bb84f0)
![image](https://github.com/user-attachments/assets/0f72a2b7-1cb2-497f-bfce-ca03012a87b6)
![image](https://github.com/user-attachments/assets/2a8c30a2-bc13-4931-b2a6-d98c9cd2c755)
![image](https://github.com/user-attachments/assets/12f0e134-9291-4bf0-90f2-5480acfa7ca5)

### System & Environment

1. Device and OS: Hono magicbook 14, Ubuntu 22.04.4 LTS
2. Browser: Google chrome
3. Version number of the application: 128.0.6613.113 (Official Build) (64-bit)
4. How you include the script: First installed using `npm i add-to-caledar-button-react` to install the library and importing using `import { AddToCaledarButton} from "add-to-caledar-button-react"`

**Comment by jekuer** [comment]
@itsritiksharma , does it work with "04:00" instead of "4:00"? And if you add the debug attribute, any output?

**Comment by itsritiksharma** [comment]
@jekuer This worked but wouldn't it be counter intuitive to not accept the "4:00" format? Just to make calendar button work and  use "04:00" I'll have to add one more line of code in my program.

**Comment by jekuer** [comment]
Will think about that.
Thing is. The format hh:mm with leading zeros is the usual way of working with date times.
So, it is one line for you vs. 1 line for everybody where 99% would not need it.
But maybe I find a nice "hack" for the future.
