### ISSUE TITLE
Support for Google Calendar on iOS with recurring events

### ISSUE THREAD

**Issue by mkecman** [add2cal/add-to-calendar-button#623]
Hi there, 
Amazing project, thank you so much for making it! 

I want my users to have Google calendar on their iOS devices, and it works fine unless I define the event to be recurring! 
As per the documentation:
> Defines recurring events: This will deactivate the Yahoo and Microsoft (and **Google at iOS**) options, since they do not support it at the moment (users could still use iCal in this case). If no option is left then, iCal will be set as fallback.

I'm wondering if this is still the case? Because you can easily set a recurring event in the Google calendar app. 

Cheers!

**Comment by jekuer** [comment]
Hi @mkecman ,

You could test the following link: [https://calendar.google.com/calendar/u/0/r/eventedit?dates=20240925T100000%2F20240925T120000&ctz=GMT&text=Test&recur=RRULE:FREQ%3DWEEKLY;WKST%3DMO;INTERVAL%3D1](https://calendar.google.com/calendar/u/0/r/eventedit?dates=20240925T100000%2F20240925T120000&ctz=GMT&text=Test&recur=RRULE:FREQ%3DWEEKLY;WKST%3DMO;INTERVAL%3D1)
If this works on your iOS device, then they might have fixed it and we can revert the workaround. 😃 .

Thanks for your support!

**Comment by jekuer** [comment]
Tested it myself now. Not supported yet.
