### ISSUE TITLE
[Bug]: Does not support google calendar organizer emails

### ISSUE THREAD

**Issue by brenjt** [add2cal/add-to-calendar-button#625]
### What happened?

Cannot use custom google calendars as organizer. Additional Google Calendar emails are long and look like this:
`c_6745f58b4d80d12c7d81b98ba112eec40ea99c21f24b27ba8c56d302bba0255c@group.calendar.google.com`. These types of emails do not validate because they are longer than the arbitrary 80 character limit here whereas these emails are 92.

https://github.com/add2cal/add-to-calendar-button/blob/19e81f30dcbde4d4002e21be41c42d025e9bbfef/src/atcb-validate.js#L231

### System & Environment

Version Number: 2.6.19

**Comment by jekuer** [comment]
Reasonable. Thank you.
Already merged, but need to put it into the next package/version.
