### ISSUE TITLE
Do not remove Elements directly, but remove Childs of the parent - to not conflict with Flutter

### ISSUE THREAD

**Issue by hardiklakhalani** [add2cal/add-to-calendar-button#631]
### What happened?

```
Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at Element.remove (v3.js:1:699)
    at atcb.js:2171:27
    at Array.forEach (<anonymous>)
    at W (atcb.js:2171:8)
    at G (atcb.js:2019:5)
    at atcb.js:3177:9
    at HTMLDivElement.<anonymous> (atcb.js:4836:12)
Element.remove @ v3.js:1
(anonymous) @ atcb.js:2171
W @ atcb.js:2171
G @ atcb.js:2019
(anonymous) @ atcb.js:3177
(anonymous) @ atcb.js:4836
```

### How to reproduce?

I have a for loop of appointments, each div element has one  <add-to-calendar-button>
When I click on the button, it opens the dropdown as expected, but when I `(click outside to close || click on button again to close || click on any calendar choice)` I get this error, Cursor stays as Cross Icon, unable to click anywhere.

### Screenshots & more

![image](https://github.com/user-attachments/assets/63a7912b-7d03-4b90-9de7-7f4d9fb7856f)

### System & Environment

1. Device and OS: Windows 10
2. Browser: Google Chrome
3. Version number of the application: Version 128.0.6613.138 (Official Build) (64-bit)
4. How you include the script: CDN, <script src="https://cdn.jsdelivr.net/npm/add-to-calendar-button@2" async defer></script>

**Comment by jekuer** [comment]
Hi @hardiklakhalani , is there a live webpage, where I can see this in action?
Or maybe you can share the code here?

**Comment by hardiklakhalani** [comment]
@jekuer  Sure, here it is:
https://eventrights.saasmonks.in/my-tickets
Demo Credentials:
`demouser@saasmonks.in`
`123456`

**Comment by jekuer** [comment]
This does not seem to be a bug on our side. It seems like Flutter is intercepting any removal of a shadowDom element and trying to remove it as well. However, as at this very moment, the element got already removed, Flutter runs into an error.
This feels like a workaround on the Flutter side to make sure things are cleaned up, but without proper error handling.

An option would (maybe!) be to not remove elements directly, but copy the Flutter approach to select the parent and then remove the child of it. Not sure, if possible. Needs more investigation.
However, not really a "Bug" - more a feature request.

**Comment by hardiklakhalani** [comment]
There's no Flutter here. This is made with Laravel Blade, HTML, Tailwind. And I only placed Add-to-calendar-button & cdn.. and not doing any removal manually from my side. Issue is the same when hovering over the button.

**Comment by jekuer** [comment]
You are right. The file name in combination with your profile misled me.
![image](https://github.com/user-attachments/assets/3f9637e1-3010-48d3-ab62-9a2c8f769be6)
![image](https://github.com/user-attachments/assets/fe9dbd14-2362-483c-9008-cddb811b4be7)

Then it is even a won'tfix.

Btw: Mind that you are not allowed to sell this as a feature per license agreement. I guess, if it only there on those user profile pages, it is ok. Maybe keep the branding to be safe. 😃

**Comment by jekuer** [comment]
This checkout.flutterwave thing intercepts core JS behavior.
