### ISSUE TITLE
Feature request: choice click callback

### ISSUE THREAD

**Issue by justin-hackin** [add2cal/add-to-calendar-button#645]
I want to be able to use Google Analytics to track choice clicks by the option name. I would like to see an option property `onOptionClick` of type `(option: string)=>void | boolean` where option is in the config options choices. If the function returns true, the default action will be omitted.

**Comment by justin-hackin** [comment]
Oh jeez, I just realized this project uses custom elements 😬 so this will probably never happen 🤷🏻‍♂️

**Comment by jekuer** [comment]
For GA, there is an even easier solution. We are already pushing this information to the DataLayer. See https://add-to-calendar-button.com/advanced-use#case-7

Will enhance in the future.
