### ISSUE TITLE
[Bug]: ListStyle is set to "overlay" when hideTextLabelButton is true

### ISSUE THREAD

**Issue by MarianaReis1** [add2cal/add-to-calendar-button#647]
### What happened?

`ListStyle` prop is being ignored and automatically set to be `overlay` when `hideTextLabelButton` is true.

### How to reproduce?

Pass the prop `hideTextLabelButton` and the listStyle will change to be `overlay`.
Then change the listStyle to any other type like `dropdown-static` and it does not work. 
Only if you pass `listStyle: 'modal'` works. 

### Screenshots & more

https://github.com/user-attachments/assets/542ede29-520d-4842-82b5-6fde4f3667f3

### System & Environment

1. Device and OS: Mac IOS
2. Browser: Chrome Version 130.0.6723.70 
3. Version number of the application:
4. How you include the script: used `add-to-calendar-button-react@^2.7.3`

**Comment by jekuer** [comment]
This is no bug, but a feature 😃 .
The button realizes that a dropdown would not work with this style and such a small triggering button (as the label is missing).
You can try another button style (like the rounded one), which does not act as a traditional dropdown and therefore keeps the intended behavior.
