### ISSUE TITLE
downloads not working in in-app browser (instagram)

### ISSUE THREAD

**Issue by svchostdotexe** [add2cal/add-to-calendar-button#72]
Somehow the Apple and ICS version are broken (do nothing) in the instagram in-app browser. I tried to find out why, because apparently other downloads work, so it is not an issue with instagram, but i could not verify that.

would be great if this was fixed, because this totally breaks this tool for us.

PS: thank you for the awesome package, otherwise it is working perfectly and looks clean and polished!

**Comment by jekuer** [comment]
Thanks for the observation. The in-app chrome browser at Instagram is blocking some part of the process. Need to figure out which part. It is working at the (for example) LinkedIn in-app browser.

**Comment by jekuer** [comment]
I have a potential solution in mind. Will need some more days for implementation. Would be really cool, if you could support testing it afterwards :)

**Comment by svchostdotexe** [comment]
sure thing, happy to help!

**Comment by svchostdotexe** [comment]
any updates on this? can i help somehow?

**Comment by jekuer** [comment]
Expect some updates towards end of this week.

**Comment by jekuer** [comment]
Implemented with the latest 1.11 release - at least a first try.
It would be really cool if you could test it on your side.

Logic:
When Instagram is detected, we show a note instead of the download and copy the file into the user's clipboard.
EXCEPT, the button holds an explicit iCal file (also new functionality) (example 3 at the demo page includes that) - and hopefully this works directly with Instagram.

**Comment by jekuer** [comment]
First Update:
With Android, explicit file option works, fallback does not - copying to clipboard is blocked - will try a small rework soon.

**Comment by svchostdotexe** [comment]
sorry for the late reaction, i sadly don't have a working computer on me right now. The fix with the note works great and is really similar to our current fix. The ability to customize the note would be awesome. Right now it feels a bit out of touch with the rest of our product. Further more: downloads work for android in general, so if detecting ios is as simple as detecting instagram it would be cool to display the message only if(ios&&instagram). 

the explicit ical does not work for ios (at least i got told that it does not work, do not own an ios device myself)

thank you for your work!

**Comment by jekuer** [comment]
Unfortunately, we cannot simply do iOS+Instagram, because I also experienced problems with Android in some cases. However, using the explicit iCal file solved it for Android. If it does not work for iOS, we would need to show the info note also in the case explicit+iOS+Instagram (that would be new).

In terms of customization: Do you mean the text only or the whole style?

**Comment by svchostdotexe** [comment]
oh, yes sure if android is also problematic then the note is needed there too. But are you sure it is the same problem? From my research all android devices should redirect to the real browser as far as i can tell. (With the old button it was not the case weirdly, but all other downloads work for me in that way)

explicit + ios + insta does not work for my coworker. 

for our case i think the style is fine (but others might want to customize that too), but we would need to customize all text inside the box to make it fit our style of communication.

**Comment by jekuer** [comment]
This recently got optimized again to support all WebView situations. It also fixes the explicit+ios thing.

Plus: You can now override any static text block.
You can see potential identifiers at the bottom of the js file - but also find the current ones below (the first 2 can be also overriden by the config option `label` or setting a custom label for the iCal function with `|` at the option):

```
case 'Add to Calendar':
  return 'Add to Calendar';
case 'iCal File':
  return 'iCal File';
case 'Close':
  return 'Close';
case 'Close Selection':
  return 'Close Selection';
case 'Click me':
  return 'Click me';
case 'WebView iCal':
  return 'Open your browser';
case 'WebView info description':
  return "Unfortunately, in-app browsers have problems with the way we generate the calendar file.<br>We automatically put a magical URL into your phone's clipboard.<br><ol><li><strong>Open any other browser</strong> on your phone, ...</li><li><strong>Paste</strong> the clipboard content and go.";
```


**How this works:**
Set the option `customLabels` and provide a JSON object where the key would be the text block's identifier (lower case without spaces). See the bottom of the js file for possible text blocks. You can use HTML pseudo tags, which get transformed automatically. Suported ones: [url] (see next point), [br], [hr], [p], [strong], [u], [i], [em], [li], [ul], [ol], [h*] (like h1, h2, h3, ...). Mind that those pseudo elements only work for the big text blocks, which currently isonly the last one.

**Example** for the 'WebView info description' case:
`"customLabels":{"webviewinfodescription":"My [u]new[/u] text block"},`
