### ISSUE TITLE
Ability to pass style props in to react component

### ISSUE THREAD

**Issue by airowe** [add2cal/add-to-calendar-button#97]
I would like to use the built-in atcb button class as part of this library in React/Typescript, but am unable to style specific properties via this method. Specifically, I'd like to remove the drop shadow behind the button component if possible. Can you expose that ability or allow this shadow to be controlled by a prop? 

Otherwise, it's working fabulously.

**Comment by jekuer** [comment]
Planned in the way, that you can choose from different style options per button. This shall include a "none" option, where you would need to define the style completely on your own.

**Comment by xtravagant** [comment]
Hi,

I noticed that the behaviour of using the atcb_action is different from using the <div class="atcb".... codes. 

Basically, I only wanted to use the iCal option.

If I use the atcb_action, a popup message will display. Unlike using the <div class="atcb .., the .ics file will be automatically downloaded. How do I achieve this behavior if I use the atcb_action?

**Comment by terrytjw** [comment]
Hi! How do I change the styles of the modal pop up, considering there are no style props exposed at the moment.

**Comment by jekuer** [comment]
@terrytjw , check out the css files in the repo, copy the one you like the most. Adjust it. Load it instead of the official one.

Alternatively, you could also simply override the css (but not so stable looking forward).

**Comment by jekuer** [comment]
Now possible with V2. Checkout https://add-to-calendar-button.com/en/advanced-use for documentation.
